/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  SearchApiV1SearchGetParams,
  SrcApiRoutesSearchSearchResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Search teams by name, short_name or TLA and matches by team names. Uses PostgreSQL ilike for case-insensitive partial matching.
 * @summary Search teams and matches
 */
export type searchApiV1SearchGetResponse200 = {
  data: SrcApiRoutesSearchSearchResponse
  status: 200
}

export type searchApiV1SearchGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type searchApiV1SearchGetResponseSuccess = (searchApiV1SearchGetResponse200) & {
  headers: Headers;
};
export type searchApiV1SearchGetResponseError = (searchApiV1SearchGetResponse422) & {
  headers: Headers;
};

export type searchApiV1SearchGetResponse = (searchApiV1SearchGetResponseSuccess | searchApiV1SearchGetResponseError)

export const getSearchApiV1SearchGetUrl = (params: SearchApiV1SearchGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/search?${stringifiedParams}` : `/api/v1/search`
}

export const searchApiV1SearchGet = async (params: SearchApiV1SearchGetParams, options?: RequestInit): Promise<searchApiV1SearchGetResponse> => {
  
  return customInstance<searchApiV1SearchGetResponse>(getSearchApiV1SearchGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSearchApiV1SearchGetQueryKey = (params?: SearchApiV1SearchGetParams,) => {
    return [
    `/api/v1/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchApiV1SearchGetQueryOptions = <TData = Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError = HTTPValidationError>(params: SearchApiV1SearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchApiV1SearchGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchApiV1SearchGet>>> = ({ signal }) => searchApiV1SearchGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchApiV1SearchGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchApiV1SearchGet>>>
export type SearchApiV1SearchGetQueryError = HTTPValidationError


export function useSearchApiV1SearchGet<TData = Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError = HTTPValidationError>(
 params: SearchApiV1SearchGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchApiV1SearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchApiV1SearchGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApiV1SearchGet<TData = Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError = HTTPValidationError>(
 params: SearchApiV1SearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchApiV1SearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchApiV1SearchGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApiV1SearchGet<TData = Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError = HTTPValidationError>(
 params: SearchApiV1SearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search teams and matches
 */

export function useSearchApiV1SearchGet<TData = Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError = HTTPValidationError>(
 params: SearchApiV1SearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchApiV1SearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchApiV1SearchGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




