/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FavoriteCreate,
  FavoriteListResponse,
  FavoriteResponse,
  HTTPErrorResponse,
  HTTPValidationError,
  PreferencesResponse,
  PreferencesUpdate,
  RemoveFavoriteApiV1UserFavoritesMatchIdDelete200
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List user's favorite picks with match details.
 * @summary List Favorites
 */
export type listFavoritesApiV1UserFavoritesGetResponse200 = {
  data: FavoriteListResponse
  status: 200
}

export type listFavoritesApiV1UserFavoritesGetResponse401 = {
  data: HTTPErrorResponse
  status: 401
}
    
export type listFavoritesApiV1UserFavoritesGetResponseSuccess = (listFavoritesApiV1UserFavoritesGetResponse200) & {
  headers: Headers;
};
export type listFavoritesApiV1UserFavoritesGetResponseError = (listFavoritesApiV1UserFavoritesGetResponse401) & {
  headers: Headers;
};

export type listFavoritesApiV1UserFavoritesGetResponse = (listFavoritesApiV1UserFavoritesGetResponseSuccess | listFavoritesApiV1UserFavoritesGetResponseError)

export const getListFavoritesApiV1UserFavoritesGetUrl = () => {


  

  return `/api/v1/user/favorites`
}

export const listFavoritesApiV1UserFavoritesGet = async ( options?: RequestInit): Promise<listFavoritesApiV1UserFavoritesGetResponse> => {
  
  return customInstance<listFavoritesApiV1UserFavoritesGetResponse>(getListFavoritesApiV1UserFavoritesGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListFavoritesApiV1UserFavoritesGetQueryKey = () => {
    return [
    `/api/v1/user/favorites`
    ] as const;
    }

    
export const getListFavoritesApiV1UserFavoritesGetQueryOptions = <TData = Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError = HTTPErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFavoritesApiV1UserFavoritesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>> = ({ signal }) => listFavoritesApiV1UserFavoritesGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFavoritesApiV1UserFavoritesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>>
export type ListFavoritesApiV1UserFavoritesGetQueryError = HTTPErrorResponse


export function useListFavoritesApiV1UserFavoritesGet<TData = Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError = HTTPErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>,
          TError,
          Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFavoritesApiV1UserFavoritesGet<TData = Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>,
          TError,
          Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFavoritesApiV1UserFavoritesGet<TData = Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Favorites
 */

export function useListFavoritesApiV1UserFavoritesGet<TData = Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFavoritesApiV1UserFavoritesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFavoritesApiV1UserFavoritesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Add a pick to favorites.
 * @summary Add Favorite
 */
export type addFavoriteApiV1UserFavoritesPostResponse200 = {
  data: FavoriteResponse
  status: 200
}

export type addFavoriteApiV1UserFavoritesPostResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type addFavoriteApiV1UserFavoritesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type addFavoriteApiV1UserFavoritesPostResponseSuccess = (addFavoriteApiV1UserFavoritesPostResponse200) & {
  headers: Headers;
};
export type addFavoriteApiV1UserFavoritesPostResponseError = (addFavoriteApiV1UserFavoritesPostResponse401 | addFavoriteApiV1UserFavoritesPostResponse422) & {
  headers: Headers;
};

export type addFavoriteApiV1UserFavoritesPostResponse = (addFavoriteApiV1UserFavoritesPostResponseSuccess | addFavoriteApiV1UserFavoritesPostResponseError)

export const getAddFavoriteApiV1UserFavoritesPostUrl = () => {


  

  return `/api/v1/user/favorites`
}

export const addFavoriteApiV1UserFavoritesPost = async (favoriteCreate: FavoriteCreate, options?: RequestInit): Promise<addFavoriteApiV1UserFavoritesPostResponse> => {
  
  return customInstance<addFavoriteApiV1UserFavoritesPostResponse>(getAddFavoriteApiV1UserFavoritesPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      favoriteCreate,)
  }
);}




export const getAddFavoriteApiV1UserFavoritesPostMutationOptions = <TError = HTTPErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addFavoriteApiV1UserFavoritesPost>>, TError,{data: FavoriteCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addFavoriteApiV1UserFavoritesPost>>, TError,{data: FavoriteCreate}, TContext> => {

const mutationKey = ['addFavoriteApiV1UserFavoritesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addFavoriteApiV1UserFavoritesPost>>, {data: FavoriteCreate}> = (props) => {
          const {data} = props ?? {};

          return  addFavoriteApiV1UserFavoritesPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddFavoriteApiV1UserFavoritesPostMutationResult = NonNullable<Awaited<ReturnType<typeof addFavoriteApiV1UserFavoritesPost>>>
    export type AddFavoriteApiV1UserFavoritesPostMutationBody = FavoriteCreate
    export type AddFavoriteApiV1UserFavoritesPostMutationError = HTTPErrorResponse | HTTPValidationError

    /**
 * @summary Add Favorite
 */
export const useAddFavoriteApiV1UserFavoritesPost = <TError = HTTPErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addFavoriteApiV1UserFavoritesPost>>, TError,{data: FavoriteCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addFavoriteApiV1UserFavoritesPost>>,
        TError,
        {data: FavoriteCreate},
        TContext
      > => {
      return useMutation(getAddFavoriteApiV1UserFavoritesPostMutationOptions(options), queryClient);
    }
    /**
 * Remove a pick from favorites.
 * @summary Remove Favorite
 */
export type removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse200 = {
  data: RemoveFavoriteApiV1UserFavoritesMatchIdDelete200
  status: 200
}

export type removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type removeFavoriteApiV1UserFavoritesMatchIdDeleteResponseSuccess = (removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse200) & {
  headers: Headers;
};
export type removeFavoriteApiV1UserFavoritesMatchIdDeleteResponseError = (removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse401 | removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse422) & {
  headers: Headers;
};

export type removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse = (removeFavoriteApiV1UserFavoritesMatchIdDeleteResponseSuccess | removeFavoriteApiV1UserFavoritesMatchIdDeleteResponseError)

export const getRemoveFavoriteApiV1UserFavoritesMatchIdDeleteUrl = (matchId: number,) => {


  

  return `/api/v1/user/favorites/${matchId}`
}

export const removeFavoriteApiV1UserFavoritesMatchIdDelete = async (matchId: number, options?: RequestInit): Promise<removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse> => {
  
  return customInstance<removeFavoriteApiV1UserFavoritesMatchIdDeleteResponse>(getRemoveFavoriteApiV1UserFavoritesMatchIdDeleteUrl(matchId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getRemoveFavoriteApiV1UserFavoritesMatchIdDeleteMutationOptions = <TError = HTTPErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFavoriteApiV1UserFavoritesMatchIdDelete>>, TError,{matchId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeFavoriteApiV1UserFavoritesMatchIdDelete>>, TError,{matchId: number}, TContext> => {

const mutationKey = ['removeFavoriteApiV1UserFavoritesMatchIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeFavoriteApiV1UserFavoritesMatchIdDelete>>, {matchId: number}> = (props) => {
          const {matchId} = props ?? {};

          return  removeFavoriteApiV1UserFavoritesMatchIdDelete(matchId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveFavoriteApiV1UserFavoritesMatchIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeFavoriteApiV1UserFavoritesMatchIdDelete>>>
    
    export type RemoveFavoriteApiV1UserFavoritesMatchIdDeleteMutationError = HTTPErrorResponse | HTTPValidationError

    /**
 * @summary Remove Favorite
 */
export const useRemoveFavoriteApiV1UserFavoritesMatchIdDelete = <TError = HTTPErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFavoriteApiV1UserFavoritesMatchIdDelete>>, TError,{matchId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeFavoriteApiV1UserFavoritesMatchIdDelete>>,
        TError,
        {matchId: number},
        TContext
      > => {
      return useMutation(getRemoveFavoriteApiV1UserFavoritesMatchIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Get user preferences.
 * @summary Get Preferences
 */
export type getPreferencesApiV1UserPreferencesGetResponse200 = {
  data: PreferencesResponse
  status: 200
}

export type getPreferencesApiV1UserPreferencesGetResponse401 = {
  data: HTTPErrorResponse
  status: 401
}
    
export type getPreferencesApiV1UserPreferencesGetResponseSuccess = (getPreferencesApiV1UserPreferencesGetResponse200) & {
  headers: Headers;
};
export type getPreferencesApiV1UserPreferencesGetResponseError = (getPreferencesApiV1UserPreferencesGetResponse401) & {
  headers: Headers;
};

export type getPreferencesApiV1UserPreferencesGetResponse = (getPreferencesApiV1UserPreferencesGetResponseSuccess | getPreferencesApiV1UserPreferencesGetResponseError)

export const getGetPreferencesApiV1UserPreferencesGetUrl = () => {


  

  return `/api/v1/user/preferences`
}

export const getPreferencesApiV1UserPreferencesGet = async ( options?: RequestInit): Promise<getPreferencesApiV1UserPreferencesGetResponse> => {
  
  return customInstance<getPreferencesApiV1UserPreferencesGetResponse>(getGetPreferencesApiV1UserPreferencesGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPreferencesApiV1UserPreferencesGetQueryKey = () => {
    return [
    `/api/v1/user/preferences`
    ] as const;
    }

    
export const getGetPreferencesApiV1UserPreferencesGetQueryOptions = <TData = Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError = HTTPErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPreferencesApiV1UserPreferencesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>> = ({ signal }) => getPreferencesApiV1UserPreferencesGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPreferencesApiV1UserPreferencesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>>
export type GetPreferencesApiV1UserPreferencesGetQueryError = HTTPErrorResponse


export function useGetPreferencesApiV1UserPreferencesGet<TData = Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError = HTTPErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>,
          TError,
          Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPreferencesApiV1UserPreferencesGet<TData = Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>,
          TError,
          Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPreferencesApiV1UserPreferencesGet<TData = Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Preferences
 */

export function useGetPreferencesApiV1UserPreferencesGet<TData = Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1UserPreferencesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPreferencesApiV1UserPreferencesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update user preferences.
 * @summary Update Preferences
 */
export type updatePreferencesApiV1UserPreferencesPutResponse200 = {
  data: PreferencesResponse
  status: 200
}

export type updatePreferencesApiV1UserPreferencesPutResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type updatePreferencesApiV1UserPreferencesPutResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updatePreferencesApiV1UserPreferencesPutResponseSuccess = (updatePreferencesApiV1UserPreferencesPutResponse200) & {
  headers: Headers;
};
export type updatePreferencesApiV1UserPreferencesPutResponseError = (updatePreferencesApiV1UserPreferencesPutResponse401 | updatePreferencesApiV1UserPreferencesPutResponse422) & {
  headers: Headers;
};

export type updatePreferencesApiV1UserPreferencesPutResponse = (updatePreferencesApiV1UserPreferencesPutResponseSuccess | updatePreferencesApiV1UserPreferencesPutResponseError)

export const getUpdatePreferencesApiV1UserPreferencesPutUrl = () => {


  

  return `/api/v1/user/preferences`
}

export const updatePreferencesApiV1UserPreferencesPut = async (preferencesUpdate: PreferencesUpdate, options?: RequestInit): Promise<updatePreferencesApiV1UserPreferencesPutResponse> => {
  
  return customInstance<updatePreferencesApiV1UserPreferencesPutResponse>(getUpdatePreferencesApiV1UserPreferencesPutUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      preferencesUpdate,)
  }
);}




export const getUpdatePreferencesApiV1UserPreferencesPutMutationOptions = <TError = HTTPErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePreferencesApiV1UserPreferencesPut>>, TError,{data: PreferencesUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePreferencesApiV1UserPreferencesPut>>, TError,{data: PreferencesUpdate}, TContext> => {

const mutationKey = ['updatePreferencesApiV1UserPreferencesPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePreferencesApiV1UserPreferencesPut>>, {data: PreferencesUpdate}> = (props) => {
          const {data} = props ?? {};

          return  updatePreferencesApiV1UserPreferencesPut(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePreferencesApiV1UserPreferencesPutMutationResult = NonNullable<Awaited<ReturnType<typeof updatePreferencesApiV1UserPreferencesPut>>>
    export type UpdatePreferencesApiV1UserPreferencesPutMutationBody = PreferencesUpdate
    export type UpdatePreferencesApiV1UserPreferencesPutMutationError = HTTPErrorResponse | HTTPValidationError

    /**
 * @summary Update Preferences
 */
export const useUpdatePreferencesApiV1UserPreferencesPut = <TError = HTTPErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePreferencesApiV1UserPreferencesPut>>, TError,{data: PreferencesUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePreferencesApiV1UserPreferencesPut>>,
        TError,
        {data: PreferencesUpdate},
        TContext
      > => {
      return useMutation(getUpdatePreferencesApiV1UserPreferencesPutMutationOptions(options), queryClient);
    }
    