/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MLStatusResponse,
  PipelineResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get current ML system status
 */
export type getMlStatusResponse200 = {
  data: MLStatusResponse
  status: 200
}
    
export type getMlStatusResponseSuccess = (getMlStatusResponse200) & {
  headers: Headers;
};
;

export type getMlStatusResponse = (getMlStatusResponseSuccess)

export const getGetMlStatusUrl = () => {


  

  return `/api/v1/ml/status`
}

export const getMlStatus = async ( options?: RequestInit): Promise<getMlStatusResponse> => {
  
  return customInstance<getMlStatusResponse>(getGetMlStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMlStatusQueryKey = () => {
    return [
    `/api/v1/ml/status`
    ] as const;
    }

    
export const getGetMlStatusQueryOptions = <TData = Awaited<ReturnType<typeof getMlStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMlStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMlStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMlStatus>>> = ({ signal }) => getMlStatus({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMlStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMlStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getMlStatus>>>
export type GetMlStatusQueryError = unknown


export function useGetMlStatus<TData = Awaited<ReturnType<typeof getMlStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMlStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMlStatus>>,
          TError,
          Awaited<ReturnType<typeof getMlStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMlStatus<TData = Awaited<ReturnType<typeof getMlStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMlStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMlStatus>>,
          TError,
          Awaited<ReturnType<typeof getMlStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMlStatus<TData = Awaited<ReturnType<typeof getMlStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMlStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current ML system status
 */

export function useGetMlStatus<TData = Awaited<ReturnType<typeof getMlStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMlStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMlStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Start data collection in background
 */
export type collectDataResponse200 = {
  data: PipelineResponse
  status: 200
}

export type collectDataResponse409 = {
  data: void
  status: 409
}
    
export type collectDataResponseSuccess = (collectDataResponse200) & {
  headers: Headers;
};
export type collectDataResponseError = (collectDataResponse409) & {
  headers: Headers;
};

export type collectDataResponse = (collectDataResponseSuccess | collectDataResponseError)

export const getCollectDataUrl = () => {


  

  return `/api/v1/ml/collect`
}

export const collectData = async ( options?: RequestInit): Promise<collectDataResponse> => {
  
  return customInstance<collectDataResponse>(getCollectDataUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getCollectDataMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof collectData>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof collectData>>, TError,void, TContext> => {

const mutationKey = ['collectData'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof collectData>>, void> = () => {
          

          return  collectData(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CollectDataMutationResult = NonNullable<Awaited<ReturnType<typeof collectData>>>
    
    export type CollectDataMutationError = void

    /**
 * @summary Start data collection in background
 */
export const useCollectData = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof collectData>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof collectData>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCollectDataMutationOptions(options), queryClient);
    }
    /**
 * @summary Start model training in background
 */
export type trainModelsResponse200 = {
  data: PipelineResponse
  status: 200
}

export type trainModelsResponse409 = {
  data: void
  status: 409
}
    
export type trainModelsResponseSuccess = (trainModelsResponse200) & {
  headers: Headers;
};
export type trainModelsResponseError = (trainModelsResponse409) & {
  headers: Headers;
};

export type trainModelsResponse = (trainModelsResponseSuccess | trainModelsResponseError)

export const getTrainModelsUrl = () => {


  

  return `/api/v1/ml/train`
}

export const trainModels = async ( options?: RequestInit): Promise<trainModelsResponse> => {
  
  return customInstance<trainModelsResponse>(getTrainModelsUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getTrainModelsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trainModels>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof trainModels>>, TError,void, TContext> => {

const mutationKey = ['trainModels'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trainModels>>, void> = () => {
          

          return  trainModels(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type TrainModelsMutationResult = NonNullable<Awaited<ReturnType<typeof trainModels>>>
    
    export type TrainModelsMutationError = void

    /**
 * @summary Start model training in background
 */
export const useTrainModels = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trainModels>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trainModels>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getTrainModelsMutationOptions(options), queryClient);
    }
    /**
 * @summary Run full ML pipeline in background
 */
export type runFullPipelineResponse200 = {
  data: PipelineResponse
  status: 200
}

export type runFullPipelineResponse409 = {
  data: void
  status: 409
}
    
export type runFullPipelineResponseSuccess = (runFullPipelineResponse200) & {
  headers: Headers;
};
export type runFullPipelineResponseError = (runFullPipelineResponse409) & {
  headers: Headers;
};

export type runFullPipelineResponse = (runFullPipelineResponseSuccess | runFullPipelineResponseError)

export const getRunFullPipelineUrl = () => {


  

  return `/api/v1/ml/run-full`
}

export const runFullPipeline = async ( options?: RequestInit): Promise<runFullPipelineResponse> => {
  
  return customInstance<runFullPipelineResponse>(getRunFullPipelineUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRunFullPipelineMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runFullPipeline>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof runFullPipeline>>, TError,void, TContext> => {

const mutationKey = ['runFullPipeline'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runFullPipeline>>, void> = () => {
          

          return  runFullPipeline(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RunFullPipelineMutationResult = NonNullable<Awaited<ReturnType<typeof runFullPipeline>>>
    
    export type RunFullPipelineMutationError = void

    /**
 * @summary Run full ML pipeline in background
 */
export const useRunFullPipeline = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runFullPipeline>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runFullPipeline>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRunFullPipelineMutationOptions(options), queryClient);
    }
    /**
 * @summary Get current pipeline execution status
 */
export type getPipelineStatusResponse200 = {
  data: PipelineResponse
  status: 200
}
    
export type getPipelineStatusResponseSuccess = (getPipelineStatusResponse200) & {
  headers: Headers;
};
;

export type getPipelineStatusResponse = (getPipelineStatusResponseSuccess)

export const getGetPipelineStatusUrl = () => {


  

  return `/api/v1/ml/pipeline-status`
}

export const getPipelineStatus = async ( options?: RequestInit): Promise<getPipelineStatusResponse> => {
  
  return customInstance<getPipelineStatusResponse>(getGetPipelineStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPipelineStatusQueryKey = () => {
    return [
    `/api/v1/ml/pipeline-status`
    ] as const;
    }

    
export const getGetPipelineStatusQueryOptions = <TData = Awaited<ReturnType<typeof getPipelineStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPipelineStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPipelineStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPipelineStatus>>> = ({ signal }) => getPipelineStatus({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPipelineStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPipelineStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getPipelineStatus>>>
export type GetPipelineStatusQueryError = unknown


export function useGetPipelineStatus<TData = Awaited<ReturnType<typeof getPipelineStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPipelineStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPipelineStatus>>,
          TError,
          Awaited<ReturnType<typeof getPipelineStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPipelineStatus<TData = Awaited<ReturnType<typeof getPipelineStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPipelineStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPipelineStatus>>,
          TError,
          Awaited<ReturnType<typeof getPipelineStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPipelineStatus<TData = Awaited<ReturnType<typeof getPipelineStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPipelineStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current pipeline execution status
 */

export function useGetPipelineStatus<TData = Awaited<ReturnType<typeof getPipelineStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPipelineStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPipelineStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




