/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetRoot200
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Root endpoint
 */
export type getRootResponse200 = {
  data: GetRoot200
  status: 200
}
    
export type getRootResponseSuccess = (getRootResponse200) & {
  headers: Headers;
};
;

export type getRootResponse = (getRootResponseSuccess)

export const getGetRootUrl = () => {


  

  return `/`
}

export const getRoot = async ( options?: RequestInit): Promise<getRootResponse> => {
  
  return customInstance<getRootResponse>(getGetRootUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetRootQueryKey = () => {
    return [
    `/`
    ] as const;
    }

    
export const getGetRootQueryOptions = <TData = Awaited<ReturnType<typeof getRoot>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRootQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoot>>> = ({ signal }) => getRoot({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRoot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRootQueryResult = NonNullable<Awaited<ReturnType<typeof getRoot>>>
export type GetRootQueryError = unknown


export function useGetRoot<TData = Awaited<ReturnType<typeof getRoot>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoot>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoot>>,
          TError,
          Awaited<ReturnType<typeof getRoot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoot<TData = Awaited<ReturnType<typeof getRoot>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoot>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoot>>,
          TError,
          Awaited<ReturnType<typeof getRoot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoot<TData = Awaited<ReturnType<typeof getRoot>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Root endpoint
 */

export function useGetRoot<TData = Awaited<ReturnType<typeof getRoot>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRootQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




