"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { format } from "date-fns";
import { fr, enUS } from "date-fns/locale";
import type { Locale } from "date-fns/locale";
import { useTranslations, useLocale } from "next-intl";
import {
  Users,
  Crown,
  TrendingUp,
  BarChart3,
  RefreshCw,
  Database,
  Loader2,
  CheckCircle,
  AlertTriangle,
  Shield,
  Search,
  ChevronLeft,
  ChevronRight,
  UserCog,
  Activity,
  Target,
  Percent,
  Trophy,
  Clock,
  Server,
  Zap,
  Gauge,
  AlertCircle,
  CheckCircle2,
  XCircle,
} from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { getAuthToken } from "@/lib/auth/token-store";
import { useGetAdminStatsApiV1AdminStatsGet, useListUsersApiV1AdminUsersGet, useUpdateUserRoleApiV1AdminUsersUserIdRolePost } from "@/lib/api/endpoints/admin/admin";
import { useGetPredictionStats } from "@/lib/api/endpoints/predictions/predictions";
import {
  useSyncWeeklyDataApiV1SyncWeeklyPost,
  useSyncMatchesOnlyApiV1SyncMatchesPost,
  useSyncStandingsOnlyApiV1SyncStandingsPost,
} from "@/lib/api/endpoints/data-sync/data-sync";
// useReadinessCheckHealthReadyGet reserved for future use
import { cn } from "@/lib/utils";
import { logger } from "@/lib/logger";

// Data Quality types (not generated by Orval yet)
interface DataQualityCheck {
  name: string;
  status: "ok" | "warning" | "critical";
  message: string;
  value?: number | string;
  threshold?: number | string;
}

interface DataQualityReport {
  timestamp: string;
  overall_status: "ok" | "warning" | "critical";
  freshness: DataQualityCheck;
  completeness: DataQualityCheck;
  range_validation: DataQualityCheck;
  consistency: DataQualityCheck;
  anomalies: { type: string; description: string }[];
}

// API Health state
interface ApiHealthState {
  status: "checking" | "healthy" | "degraded" | "down";
  latency: number | null;
  database: boolean;
  redis: boolean;
  footballApi: boolean;
  llmApi: boolean;
  lastCheck: Date | null;
}

interface StatCardProps {
  title: string;
  value: string | number;
  icon: React.ReactNode;
  trend?: string;
  trendUp?: boolean;
  subtitle?: string;
}

function StatCard({ title, value, icon, trend, trendUp, subtitle }: StatCardProps) {
  return (
    <div className="bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 rounded-xl p-6">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-gray-500 dark:text-dark-400">{title}</p>
          <p className="text-2xl font-bold text-gray-900 dark:text-white mt-1">
            {value}
          </p>
          {trend && (
            <p
              className={`text-sm mt-1 ${
                trendUp
                  ? "text-primary-600 dark:text-primary-400"
                  : "text-red-600 dark:text-red-400"
              }`}
            >
              {trendUp ? "+" : ""}
              {trend}
            </p>
          )}
          {subtitle && (
            <p className="text-xs text-gray-400 dark:text-dark-500 mt-1">
              {subtitle}
            </p>
          )}
        </div>
        <div className="p-3 bg-primary-100 dark:bg-primary-500/20 rounded-lg">
          {icon}
        </div>
      </div>
    </div>
  );
}

interface SyncOption {
  id: string;
  label: string;
  description: string;
  checked: boolean;
}

export default function AdminPage() {
  const router = useRouter();
  const { loading, isAuthenticated, isAdmin } = useAuth();
  const t = useTranslations("admin");
  // const _tCommon = useTranslations("common"); // Reserved for future use
  const locale = useLocale();
  const dateLocale: Locale = locale === "fr" ? fr : enUS;
  const [syncResult, setSyncResult] = useState<"success" | "error" | null>(null);
  const [userSearchQuery, setUserSearchQuery] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [updatingUserId, setUpdatingUserId] = useState<string | null>(null);
  const usersPerPage = 10;

  // API Health state
  const [apiHealth, setApiHealth] = useState<ApiHealthState>({
    status: "checking",
    latency: null,
    database: false,
    redis: false,
    footballApi: false,
    llmApi: false,
    lastCheck: null,
  });

  // Data Quality state
  const [dataQuality, setDataQuality] = useState<DataQualityReport | null>(null);
  const [dataQualityLoading, setDataQualityLoading] = useState(false);

  const [syncOptions, setSyncOptions] = useState<SyncOption[]>([
    {
      id: "matches",
      label: "Matchs",
      description: "Synchroniser les matchs depuis football-data.org",
      checked: true,
    },
    {
      id: "standings",
      label: "Classements",
      description: "Mettre a jour les classements des ligues",
      checked: true,
    },
    {
      id: "xg",
      label: "xG Data",
      description: "Recuperer les donnees Expected Goals",
      checked: false,
    },
  ]);

  // Fetch admin stats from API
  const { data: statsResponse, isLoading: statsLoading, refetch: refetchStats } =
    useGetAdminStatsApiV1AdminStatsGet({
      query: { enabled: isAuthenticated && isAdmin },
    });

  // Fetch prediction stats
  const { data: predictionStatsResponse, isLoading: predictionStatsLoading } =
    useGetPredictionStats(undefined, {
      query: { enabled: isAuthenticated && isAdmin },
    });

  // Fetch users list
  const { data: usersResponse, isLoading: usersLoading, refetch: refetchUsers } =
    useListUsersApiV1AdminUsersGet(
      { page: currentPage, per_page: usersPerPage },
      { query: { enabled: isAuthenticated && isAdmin } }
    );

  // Health check with latency measurement
  const checkApiHealth = useCallback(async () => {
    const startTime = performance.now();
    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
      const response = await fetch(`${apiUrl}/health/ready`);
      const latency = Math.round(performance.now() - startTime);

      if (response.ok) {
        const data = await response.json();
        setApiHealth({
          status: latency > 1000 ? "degraded" : "healthy",
          latency,
          database: data.database ?? false,
          redis: data.redis ?? false,
          footballApi: data.football_api ?? false,
          llmApi: data.llm_api ?? false,
          lastCheck: new Date(),
        });
      } else {
        setApiHealth((prev) => ({
          ...prev,
          status: "degraded",
          latency,
          lastCheck: new Date(),
        }));
      }
    } catch {
      setApiHealth((prev) => ({
        ...prev,
        status: "down",
        latency: null,
        lastCheck: new Date(),
      }));
    }
  }, []);

  // Fetch data quality report
  const fetchDataQuality = useCallback(async () => {
    setDataQualityLoading(true);
    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
      const token = getAuthToken();
      if (!token) {
        logger.warn("[Admin] No auth token available for data quality fetch");
        setDataQualityLoading(false);
        return;
      }
      const response = await fetch(`${apiUrl}/api/v1/admin/data-quality`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      if (response.ok) {
        const data = await response.json();
        setDataQuality(data);
      }
    } catch (error) {
      logger.error("Failed to fetch data quality:", error);
    } finally {
      setDataQualityLoading(false);
    }
  }, []);

  // Initial health check and data quality fetch
  useEffect(() => {
    if (isAuthenticated && isAdmin) {
      checkApiHealth();
      fetchDataQuality();

      // Refresh health every 30 seconds
      const healthInterval = setInterval(checkApiHealth, 30000);
      return () => clearInterval(healthInterval);
    }
  }, [isAuthenticated, isAdmin, checkApiHealth, fetchDataQuality]);

  // Update user role mutation
  const updateUserRole = useUpdateUserRoleApiV1AdminUsersUserIdRolePost();

  // Sync mutations
  const weeklySync = useSyncWeeklyDataApiV1SyncWeeklyPost();
  const matchesSync = useSyncMatchesOnlyApiV1SyncMatchesPost();
  const standingsSync = useSyncStandingsOnlyApiV1SyncStandingsPost();

  const isSyncing =
    weeklySync.isPending || matchesSync.isPending || standingsSync.isPending;

  // Loading state
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary-500" />
      </div>
    );
  }

  // Auth check - redirect if not admin
  if (!isAuthenticated || !isAdmin) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <Shield className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
            {t("accessDenied")}
          </h1>
          <p className="text-gray-600 dark:text-dark-400 mb-4">
            {t("noPermission")}
          </p>
          <button
            onClick={() => router.push("/")}
            className="text-primary-600 dark:text-primary-400 hover:underline"
          >
            {t("backToHome")}
          </button>
        </div>
      </div>
    );
  }

  const handleSyncToggle = (optionId: string) => {
    setSyncOptions((prev) =>
      prev.map((opt) =>
        opt.id === optionId ? { ...opt, checked: !opt.checked } : opt
      )
    );
  };

  const handleSync = async () => {
    const selectedOptions = syncOptions.filter((opt) => opt.checked);
    if (selectedOptions.length === 0) return;

    setSyncResult(null);

    try {
      const hasMatches = selectedOptions.some((o) => o.id === "matches");
      const hasStandings = selectedOptions.some((o) => o.id === "standings");

      if (hasMatches && hasStandings) {
        await weeklySync.mutateAsync({ params: { days: 7, include_standings: true } });
      } else if (hasMatches) {
        await matchesSync.mutateAsync({ params: { days: 7 } });
      } else if (hasStandings) {
        await standingsSync.mutateAsync();
      }

      setSyncResult("success");
      refetchStats();
    } catch {
      setSyncResult("error");
    }
  };

  const handleRoleChange = async (userId: string, newRole: string) => {
    setUpdatingUserId(userId);
    try {
      await updateUserRole.mutateAsync({
        userId,
        params: { role: newRole },
      });
      refetchUsers();
    } catch (error) {
      logger.error("Failed to update role:", error);
    } finally {
      setUpdatingUserId(null);
    }
  };

  // Get stats from API response
  const apiStats = statsResponse?.status === 200 ? statsResponse.data : null;
  const predictionStats = predictionStatsResponse?.status === 200 ? predictionStatsResponse.data : null;
  const usersData = usersResponse?.status === 200 ? usersResponse.data : null;

  const stats = {
    totalUsers: apiStats?.total_users ?? 0,
    premiumUsers: apiStats?.premium_users ?? 0,
    totalPredictions: apiStats?.total_predictions ?? 0,
    successRate: apiStats?.success_rate ?? 0,
    totalMatches: apiStats?.total_matches ?? 0,
    lastMatchSync: apiStats?.last_match_sync ?? null,
  };

  // Filter users by search query
  const filteredUsers = usersData?.users?.filter(
    (user) =>
      user.email.toLowerCase().includes(userSearchQuery.toLowerCase()) ||
      user.role.toLowerCase().includes(userSearchQuery.toLowerCase())
  ) ?? [];

  const totalPages = Math.ceil((usersData?.total ?? 0) / usersPerPage);

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex items-center gap-3 mb-8">
        <div className="p-2 bg-red-100 dark:bg-red-500/20 rounded-lg">
          <Shield className="w-6 h-6 text-red-600 dark:text-red-400" />
        </div>
        <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white">
          {t("title")}
        </h1>
      </div>

      {/* Stats Grid - Row 1 */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
        <StatCard
          title={t("stats.totalUsers")}
          value={statsLoading ? "..." : stats.totalUsers.toLocaleString()}
          icon={<Users className="w-6 h-6 text-primary-600 dark:text-primary-400" />}
        />
        <StatCard
          title={t("stats.premiumUsers")}
          value={statsLoading ? "..." : stats.premiumUsers}
          icon={<Crown className="w-6 h-6 text-yellow-600 dark:text-yellow-400" />}
          subtitle={stats.totalUsers > 0 ? t("stats.ofTotal", { percent: ((stats.premiumUsers / stats.totalUsers) * 100).toFixed(1) }) : undefined}
        />
        <StatCard
          title={t("stats.predictionsGenerated")}
          value={statsLoading ? "..." : stats.totalPredictions.toLocaleString()}
          icon={<TrendingUp className="w-6 h-6 text-primary-600 dark:text-primary-400" />}
        />
        <StatCard
          title={t("stats.successRate")}
          value={statsLoading ? "..." : `${stats.successRate}%`}
          icon={<BarChart3 className="w-6 h-6 text-primary-600 dark:text-primary-400" />}
        />
      </div>

      {/* Stats Grid - Row 2 */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <StatCard
          title={t("stats.matchesInDb")}
          value={statsLoading ? "..." : stats.totalMatches.toLocaleString()}
          icon={<Activity className="w-6 h-6 text-blue-600 dark:text-blue-400" />}
        />
        <StatCard
          title={t("stats.lastSync")}
          value={stats.lastMatchSync ? format(new Date(stats.lastMatchSync), "dd/MM HH:mm") : t("stats.never")}
          icon={<Clock className="w-6 h-6 text-purple-600 dark:text-purple-400" />}
        />
        {predictionStats && (
          <>
            <StatCard
              title={t("stats.correctPredictions")}
              value={predictionStatsLoading ? "..." : predictionStats.correct_predictions}
              icon={<Target className="w-6 h-6 text-primary-600 dark:text-primary-400" />}
              subtitle={t("stats.outOf", { count: predictionStats.total_predictions })}
            />
            <StatCard
              title={t("stats.simulatedRoi")}
              value={predictionStatsLoading ? "..." : `${(predictionStats.roi_simulated * 100).toFixed(1)}%`}
              icon={<Trophy className="w-6 h-6 text-yellow-600 dark:text-yellow-400" />}
            />
          </>
        )}
      </div>

      {/* Prediction Performance by Competition */}
      {predictionStats?.by_competition && Object.keys(predictionStats.by_competition).length > 0 && (
        <section className="bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 rounded-xl overflow-hidden mb-8">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-dark-700 flex items-center gap-2">
            <Percent className="w-5 h-5 text-gray-500 dark:text-dark-400" />
            <h2 className="font-semibold text-gray-900 dark:text-white">
              {t("competition.title")}
            </h2>
          </div>
          <div className="p-6">
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">
              {Object.entries(predictionStats.by_competition).map(([comp, data]) => (
                <div
                  key={comp}
                  className="bg-gray-50 dark:bg-dark-800 rounded-lg p-4 text-center"
                >
                  <p className="text-xs text-gray-500 dark:text-dark-400 mb-1">{comp}</p>
                  <p className={cn(
                    "text-2xl font-bold",
                    (data as { accuracy?: number }).accuracy && (data as { accuracy: number }).accuracy >= 60
                      ? "text-primary-600 dark:text-primary-400"
                      : (data as { accuracy?: number }).accuracy && (data as { accuracy: number }).accuracy >= 50
                      ? "text-yellow-600 dark:text-yellow-400"
                      : "text-red-600 dark:text-red-400"
                  )}>
                    {(data as { accuracy?: number }).accuracy?.toFixed(1) ?? "-"}%
                  </p>
                  <p className="text-xs text-gray-400 dark:text-dark-500 mt-1">
                    {(data as { total?: number }).total ?? 0} {t("competition.predictions")}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Data Sync Section */}
      <section className="bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 rounded-xl overflow-hidden mb-8">
        <div className="px-6 py-4 border-b border-gray-200 dark:border-dark-700 flex items-center gap-2">
          <Database className="w-5 h-5 text-gray-500 dark:text-dark-400" />
          <h2 className="font-semibold text-gray-900 dark:text-white">
            {t("sync.title")}
          </h2>
        </div>
        <div className="p-6">
          <div className="space-y-4 mb-6">
            {syncOptions.map((option) => {
              const labelKey = option.id === "matches" ? "sync.matches" : option.id === "standings" ? "sync.standings" : "sync.xgData";
              const descKey = option.id === "matches" ? "sync.matchesDesc" : option.id === "standings" ? "sync.standingsDesc" : "sync.xgDataDesc";
              return (
                <label
                  key={option.id}
                  className="flex items-start gap-3 cursor-pointer"
                >
                  <input
                    type="checkbox"
                    checked={option.checked}
                    onChange={() => handleSyncToggle(option.id)}
                    className="mt-1 w-4 h-4 rounded border-gray-300 dark:border-dark-600 text-primary-500 focus:ring-primary-500"
                  />
                  <div>
                    <p className="font-medium text-gray-900 dark:text-white">
                      {t(labelKey)}
                    </p>
                    <p className="text-sm text-gray-500 dark:text-dark-400">
                      {t(descKey)}
                    </p>
                  </div>
                </label>
              );
            })}
          </div>

          <div className="flex items-center gap-4">
            <button
              onClick={handleSync}
              disabled={
                isSyncing || syncOptions.filter((o) => o.checked).length === 0
              }
              className="inline-flex items-center gap-2 px-4 py-2 bg-primary-500 hover:bg-primary-600 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
            >
              {isSyncing ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <RefreshCw className="w-4 h-4" />
              )}
              {isSyncing ? t("sync.syncing") : t("sync.startSync")}
            </button>

            {syncResult === "success" && (
              <span className="inline-flex items-center gap-1.5 text-sm text-primary-600 dark:text-primary-400">
                <CheckCircle className="w-4 h-4" />
                {t("sync.success")}
              </span>
            )}

            {syncResult === "error" && (
              <span className="inline-flex items-center gap-1.5 text-sm text-red-600 dark:text-red-400">
                <AlertTriangle className="w-4 h-4" />
                {t("sync.error")}
              </span>
            )}
          </div>
        </div>
      </section>

      {/* User Management Section */}
      <section className="bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 rounded-xl overflow-hidden mb-8">
        <div className="px-6 py-4 border-b border-gray-200 dark:border-dark-700 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <UserCog className="w-5 h-5 text-gray-500 dark:text-dark-400" />
            <h2 className="font-semibold text-gray-900 dark:text-white">
              {t("users.title")}
            </h2>
          </div>
          <span className="text-sm text-gray-500 dark:text-dark-400">
            {t("users.count", { count: usersData?.total ?? 0 })}
          </span>
        </div>

        {/* Search */}
        <div className="px-6 py-4 border-b border-gray-200 dark:border-dark-700">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              placeholder={t("users.searchPlaceholder")}
              value={userSearchQuery}
              onChange={(e) => setUserSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2 bg-gray-50 dark:bg-dark-800 border border-gray-200 dark:border-dark-700 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-dark-400 focus:outline-none focus:ring-2 focus:ring-primary-500"
            />
          </div>
        </div>

        {/* Users Table */}
        <div className="overflow-x-auto">
          {usersLoading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-primary-500" />
            </div>
          ) : filteredUsers.length === 0 ? (
            <div className="text-center py-12">
              <Users className="w-12 h-12 text-gray-300 dark:text-dark-600 mx-auto mb-3" />
              <p className="text-gray-500 dark:text-dark-400">
                {t("users.noUsers")}
              </p>
            </div>
          ) : (
            <table className="w-full">
              <thead>
                <tr className="bg-gray-50 dark:bg-dark-800">
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-dark-400 uppercase tracking-wider">
                    {t("users.email")}
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-dark-400 uppercase tracking-wider">
                    {t("users.role")}
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-dark-400 uppercase tracking-wider">
                    {t("users.registrationDate")}
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-dark-400 uppercase tracking-wider">
                    {t("users.actions")}
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 dark:divide-dark-700">
                {filteredUsers.map((user) => (
                  <tr key={user.id} className="hover:bg-gray-50 dark:hover:bg-dark-800 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-primary-100 dark:bg-primary-500/20 flex items-center justify-center text-primary-600 dark:text-primary-400 font-medium text-sm">
                          {user.email.charAt(0).toUpperCase()}
                        </div>
                        <span className="text-gray-900 dark:text-white text-sm">
                          {user.email}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span
                        className={cn(
                          "inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium",
                          user.role === "admin"
                            ? "bg-red-100 dark:bg-red-500/20 text-red-700 dark:text-red-300"
                            : user.role === "premium"
                            ? "bg-yellow-100 dark:bg-yellow-500/20 text-yellow-700 dark:text-yellow-300"
                            : "bg-gray-100 dark:bg-dark-700 text-gray-700 dark:text-dark-300"
                        )}
                      >
                        {user.role === "admin" && <Shield className="w-3 h-3" />}
                        {user.role === "premium" && <Crown className="w-3 h-3" />}
                        {user.role}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-dark-400">
                      {format(new Date(user.created_at), "dd MMM yyyy", { locale: dateLocale })}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right">
                      <select
                        value={user.role}
                        onChange={(e) => handleRoleChange(user.id, e.target.value)}
                        disabled={updatingUserId === user.id}
                        className="text-sm bg-gray-50 dark:bg-dark-800 border border-gray-200 dark:border-dark-700 rounded-lg px-3 py-1.5 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 disabled:opacity-50"
                      >
                        <option value="free">{t("users.roleFree")}</option>
                        <option value="premium">{t("users.rolePremium")}</option>
                        <option value="admin">{t("users.roleAdmin")}</option>
                      </select>
                      {updatingUserId === user.id && (
                        <Loader2 className="w-4 h-4 animate-spin inline-block ml-2 text-primary-500" />
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="px-6 py-4 border-t border-gray-200 dark:border-dark-700 flex items-center justify-between">
            <p className="text-sm text-gray-500 dark:text-dark-400">
              {t("users.page", { current: currentPage, total: totalPages })}
            </p>
            <div className="flex items-center gap-2">
              <button
                onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                disabled={currentPage === 1}
                className="p-2 rounded-lg border border-gray-200 dark:border-dark-700 hover:bg-gray-50 dark:hover:bg-dark-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                <ChevronLeft className="w-4 h-4 text-gray-600 dark:text-dark-400" />
              </button>
              <button
                onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
                disabled={currentPage === totalPages}
                className="p-2 rounded-lg border border-gray-200 dark:border-dark-700 hover:bg-gray-50 dark:hover:bg-dark-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                <ChevronRight className="w-4 h-4 text-gray-600 dark:text-dark-400" />
              </button>
            </div>
          </div>
        )}
      </section>

      {/* System Info */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Quick Actions */}
        <section className="bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 rounded-xl overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-dark-700 flex items-center gap-2">
            <Zap className="w-5 h-5 text-yellow-500" />
            <h2 className="font-semibold text-gray-900 dark:text-white">
              {t("quickActions.title")}
            </h2>
          </div>
          <div className="p-6 space-y-3">
            <button
              onClick={() => router.push("/picks")}
              className="w-full flex items-center justify-between p-3 bg-gray-50 dark:bg-dark-800 rounded-lg hover:bg-gray-100 dark:hover:bg-dark-700 transition-colors"
            >
              <span className="text-gray-700 dark:text-dark-300">{t("quickActions.viewPicks")}</span>
              <ChevronRight className="w-4 h-4 text-gray-400" />
            </button>
            <button
              onClick={() => router.push("/matches")}
              className="w-full flex items-center justify-between p-3 bg-gray-50 dark:bg-dark-800 rounded-lg hover:bg-gray-100 dark:hover:bg-dark-700 transition-colors"
            >
              <span className="text-gray-700 dark:text-dark-300">{t("quickActions.manageMatches")}</span>
              <ChevronRight className="w-4 h-4 text-gray-400" />
            </button>
            <button
              onClick={() => router.push("/standings")}
              className="w-full flex items-center justify-between p-3 bg-gray-50 dark:bg-dark-800 rounded-lg hover:bg-gray-100 dark:hover:bg-dark-700 transition-colors"
            >
              <span className="text-gray-700 dark:text-dark-300">{t("quickActions.viewStandings")}</span>
              <ChevronRight className="w-4 h-4 text-gray-400" />
            </button>
          </div>
        </section>

        {/* System Status - Real-time */}
        <section className="bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 rounded-xl overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-dark-700 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Server className="w-5 h-5 text-gray-500 dark:text-dark-400" />
              <h2 className="font-semibold text-gray-900 dark:text-white">
                {t("system.title")}
              </h2>
            </div>
            <button
              onClick={checkApiHealth}
              className="p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-dark-800 transition-colors"
              title={t("system.refresh")}
            >
              <RefreshCw className="w-4 h-4 text-gray-500 dark:text-dark-400" />
            </button>
          </div>
          <div className="p-6 space-y-4">
            {/* API Health with Latency */}
            <div className="flex items-center justify-between">
              <span className="text-gray-600 dark:text-dark-400">{t("system.apiBackend")}</span>
              <div className="flex items-center gap-2">
                {apiHealth.latency !== null && (
                  <span className={cn(
                    "text-xs font-mono",
                    apiHealth.latency < 200 ? "text-primary-600 dark:text-primary-400" :
                    apiHealth.latency < 500 ? "text-yellow-600 dark:text-yellow-400" :
                    "text-red-600 dark:text-red-400"
                  )}>
                    {apiHealth.latency}ms
                  </span>
                )}
                <span className={cn(
                  "inline-flex items-center gap-1.5 text-sm",
                  apiHealth.status === "healthy" ? "text-primary-600 dark:text-primary-400" :
                  apiHealth.status === "degraded" ? "text-yellow-600 dark:text-yellow-400" :
                  apiHealth.status === "down" ? "text-red-600 dark:text-red-400" :
                  "text-gray-500 dark:text-dark-400"
                )}>
                  <span className={cn(
                    "w-2 h-2 rounded-full",
                    apiHealth.status === "healthy" ? "bg-primary-500 animate-pulse" :
                    apiHealth.status === "degraded" ? "bg-yellow-500" :
                    apiHealth.status === "down" ? "bg-red-500" :
                    "bg-gray-400"
                  )} />
                  {apiHealth.status === "checking" ? t("system.checking") :
                   apiHealth.status === "healthy" ? t("system.online") :
                   apiHealth.status === "degraded" ? t("system.slow") : t("system.offline")}
                </span>
              </div>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-gray-600 dark:text-dark-400">{t("system.database")}</span>
              <span className={cn(
                "inline-flex items-center gap-1.5 text-sm",
                apiHealth.database ? "text-primary-600 dark:text-primary-400" : "text-red-600 dark:text-red-400"
              )}>
                <span className={cn(
                  "w-2 h-2 rounded-full",
                  apiHealth.database ? "bg-primary-500 animate-pulse" : "bg-red-500"
                )} />
                {apiHealth.database ? t("system.connected") : t("system.disconnected")}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-gray-600 dark:text-dark-400">{t("system.redisCache")}</span>
              <span className={cn(
                "inline-flex items-center gap-1.5 text-sm",
                apiHealth.redis ? "text-primary-600 dark:text-primary-400" : "text-yellow-600 dark:text-yellow-400"
              )}>
                <span className={cn(
                  "w-2 h-2 rounded-full",
                  apiHealth.redis ? "bg-primary-500 animate-pulse" : "bg-yellow-500"
                )} />
                {apiHealth.redis ? t("system.active") : t("system.inactive")}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-gray-600 dark:text-dark-400">{t("system.footballApi")}</span>
              <span className={cn(
                "inline-flex items-center gap-1.5 text-sm",
                apiHealth.footballApi ? "text-primary-600 dark:text-primary-400" : "text-red-600 dark:text-red-400"
              )}>
                <span className={cn(
                  "w-2 h-2 rounded-full",
                  apiHealth.footballApi ? "bg-primary-500 animate-pulse" : "bg-red-500"
                )} />
                {apiHealth.footballApi ? t("system.configured") : t("system.notConfigured")}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-gray-600 dark:text-dark-400">{t("system.llmApi")}</span>
              <span className={cn(
                "inline-flex items-center gap-1.5 text-sm",
                apiHealth.llmApi ? "text-primary-600 dark:text-primary-400" : "text-yellow-600 dark:text-yellow-400"
              )}>
                <span className={cn(
                  "w-2 h-2 rounded-full",
                  apiHealth.llmApi ? "bg-primary-500 animate-pulse" : "bg-yellow-500"
                )} />
                {apiHealth.llmApi ? t("system.configured") : t("system.notConfigured")}
              </span>
            </div>

            {apiHealth.lastCheck && (
              <p className="text-xs text-gray-400 dark:text-dark-500 pt-2 border-t border-gray-100 dark:border-dark-700">
                {t("system.lastCheck")} {format(apiHealth.lastCheck, "HH:mm:ss")}
              </p>
            )}
          </div>
        </section>
      </div>

      {/* Data Quality Section */}
      <section className="bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 rounded-xl overflow-hidden mt-6">
        <div className="px-6 py-4 border-b border-gray-200 dark:border-dark-700 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Gauge className="w-5 h-5 text-gray-500 dark:text-dark-400" />
            <h2 className="font-semibold text-gray-900 dark:text-white">
              {t("dataQuality.title")}
            </h2>
          </div>
          <div className="flex items-center gap-2">
            {dataQuality && (
              <span className={cn(
                "inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium",
                dataQuality.overall_status === "ok"
                  ? "bg-primary-100 dark:bg-primary-500/20 text-primary-700 dark:text-primary-300"
                  : dataQuality.overall_status === "warning"
                  ? "bg-yellow-100 dark:bg-yellow-500/20 text-yellow-700 dark:text-yellow-300"
                  : "bg-red-100 dark:bg-red-500/20 text-red-700 dark:text-red-300"
              )}>
                {dataQuality.overall_status === "ok" && <CheckCircle2 className="w-3 h-3" />}
                {dataQuality.overall_status === "warning" && <AlertCircle className="w-3 h-3" />}
                {dataQuality.overall_status === "critical" && <XCircle className="w-3 h-3" />}
                {dataQuality.overall_status === "ok" ? t("dataQuality.ok") :
                 dataQuality.overall_status === "warning" ? t("dataQuality.warning") : t("dataQuality.critical")}
              </span>
            )}
            <button
              onClick={fetchDataQuality}
              disabled={dataQualityLoading}
              className="p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-dark-800 transition-colors disabled:opacity-50"
              title={t("system.refresh")}
            >
              <RefreshCw className={cn(
                "w-4 h-4 text-gray-500 dark:text-dark-400",
                dataQualityLoading && "animate-spin"
              )} />
            </button>
          </div>
        </div>

        {dataQualityLoading && !dataQuality ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="w-8 h-8 animate-spin text-primary-500" />
          </div>
        ) : dataQuality ? (
          <div className="p-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {/* Freshness */}
              <div className={cn(
                "p-4 rounded-lg border",
                dataQuality.freshness.status === "ok"
                  ? "bg-primary-50 dark:bg-primary-500/10 border-primary-200 dark:border-primary-500/30"
                  : dataQuality.freshness.status === "warning"
                  ? "bg-yellow-50 dark:bg-yellow-500/10 border-yellow-200 dark:border-yellow-500/30"
                  : "bg-red-50 dark:bg-red-500/10 border-red-200 dark:border-red-500/30"
              )}>
                <div className="flex items-center gap-2 mb-2">
                  <Clock className={cn(
                    "w-4 h-4",
                    dataQuality.freshness.status === "ok" ? "text-primary-600 dark:text-primary-400" :
                    dataQuality.freshness.status === "warning" ? "text-yellow-600 dark:text-yellow-400" :
                    "text-red-600 dark:text-red-400"
                  )} />
                  <span className="text-sm font-medium text-gray-900 dark:text-white">
                    {t("dataQuality.freshness")}
                  </span>
                </div>
                <p className="text-xs text-gray-600 dark:text-dark-400">
                  {dataQuality.freshness.message}
                </p>
              </div>

              {/* Completeness */}
              <div className={cn(
                "p-4 rounded-lg border",
                dataQuality.completeness.status === "ok"
                  ? "bg-primary-50 dark:bg-primary-500/10 border-primary-200 dark:border-primary-500/30"
                  : dataQuality.completeness.status === "warning"
                  ? "bg-yellow-50 dark:bg-yellow-500/10 border-yellow-200 dark:border-yellow-500/30"
                  : "bg-red-50 dark:bg-red-500/10 border-red-200 dark:border-red-500/30"
              )}>
                <div className="flex items-center gap-2 mb-2">
                  <BarChart3 className={cn(
                    "w-4 h-4",
                    dataQuality.completeness.status === "ok" ? "text-primary-600 dark:text-primary-400" :
                    dataQuality.completeness.status === "warning" ? "text-yellow-600 dark:text-yellow-400" :
                    "text-red-600 dark:text-red-400"
                  )} />
                  <span className="text-sm font-medium text-gray-900 dark:text-white">
                    {t("dataQuality.completeness")}
                  </span>
                </div>
                <p className="text-xs text-gray-600 dark:text-dark-400">
                  {dataQuality.completeness.message}
                </p>
                {dataQuality.completeness.value && (
                  <p className="text-lg font-bold text-gray-900 dark:text-white mt-1">
                    {typeof dataQuality.completeness.value === 'number'
                      ? `${(dataQuality.completeness.value * 100).toFixed(0)}%`
                      : dataQuality.completeness.value}
                  </p>
                )}
              </div>

              {/* Range Validation */}
              <div className={cn(
                "p-4 rounded-lg border",
                dataQuality.range_validation.status === "ok"
                  ? "bg-primary-50 dark:bg-primary-500/10 border-primary-200 dark:border-primary-500/30"
                  : dataQuality.range_validation.status === "warning"
                  ? "bg-yellow-50 dark:bg-yellow-500/10 border-yellow-200 dark:border-yellow-500/30"
                  : "bg-red-50 dark:bg-red-500/10 border-red-200 dark:border-red-500/30"
              )}>
                <div className="flex items-center gap-2 mb-2">
                  <Target className={cn(
                    "w-4 h-4",
                    dataQuality.range_validation.status === "ok" ? "text-primary-600 dark:text-primary-400" :
                    dataQuality.range_validation.status === "warning" ? "text-yellow-600 dark:text-yellow-400" :
                    "text-red-600 dark:text-red-400"
                  )} />
                  <span className="text-sm font-medium text-gray-900 dark:text-white">
                    {t("dataQuality.validation")}
                  </span>
                </div>
                <p className="text-xs text-gray-600 dark:text-dark-400">
                  {dataQuality.range_validation.message}
                </p>
              </div>

              {/* Consistency */}
              <div className={cn(
                "p-4 rounded-lg border",
                dataQuality.consistency.status === "ok"
                  ? "bg-primary-50 dark:bg-primary-500/10 border-primary-200 dark:border-primary-500/30"
                  : dataQuality.consistency.status === "warning"
                  ? "bg-yellow-50 dark:bg-yellow-500/10 border-yellow-200 dark:border-yellow-500/30"
                  : "bg-red-50 dark:bg-red-500/10 border-red-200 dark:border-red-500/30"
              )}>
                <div className="flex items-center gap-2 mb-2">
                  <CheckCircle className={cn(
                    "w-4 h-4",
                    dataQuality.consistency.status === "ok" ? "text-primary-600 dark:text-primary-400" :
                    dataQuality.consistency.status === "warning" ? "text-yellow-600 dark:text-yellow-400" :
                    "text-red-600 dark:text-red-400"
                  )} />
                  <span className="text-sm font-medium text-gray-900 dark:text-white">
                    {t("dataQuality.consistency")}
                  </span>
                </div>
                <p className="text-xs text-gray-600 dark:text-dark-400">
                  {dataQuality.consistency.message}
                </p>
              </div>
            </div>

            {/* Anomalies */}
            {dataQuality.anomalies && dataQuality.anomalies.length > 0 && (
              <div className="mt-6">
                <h3 className="text-sm font-medium text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4 text-yellow-500" />
                  {t("dataQuality.anomalies", { count: dataQuality.anomalies.length })}
                </h3>
                <div className="space-y-2">
                  {dataQuality.anomalies.slice(0, 5).map((anomaly, index) => (
                    <div
                      key={index}
                      className="flex items-start gap-3 p-3 bg-yellow-50 dark:bg-yellow-500/10 rounded-lg text-sm"
                    >
                      <AlertCircle className="w-4 h-4 text-yellow-600 dark:text-yellow-400 mt-0.5 shrink-0" />
                      <div>
                        <span className="font-medium text-yellow-800 dark:text-yellow-300">
                          {anomaly.type}:
                        </span>{" "}
                        <span className="text-yellow-700 dark:text-yellow-400">
                          {anomaly.description}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {dataQuality.timestamp && (
              <p className="text-xs text-gray-400 dark:text-dark-500 mt-4 pt-4 border-t border-gray-100 dark:border-dark-700">
                {t("dataQuality.reportGenerated")} {format(new Date(dataQuality.timestamp), "dd/MM/yyyy HH:mm", { locale: dateLocale })}
              </p>
            )}
          </div>
        ) : (
          <div className="p-6 text-center text-gray-500 dark:text-dark-400">
            <AlertCircle className="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p>{t("dataQuality.loadError")}</p>
            <button
              onClick={fetchDataQuality}
              className="mt-2 text-primary-600 dark:text-primary-400 hover:underline text-sm"
            >
              {t("dataQuality.retry")}
            </button>
          </div>
        )}
      </section>
    </div>
  );
}
