/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetHeadToHeadParams,
  GetTeamFormParams,
  GetUpcomingMatchesParams,
  HeadToHeadResponse,
  ListMatchesParams,
  Match,
  MatchListResponse,
  StandingsResponse,
  TeamFormResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List matches with filters
 */
export type listMatchesResponse200 = {
  data: MatchListResponse
  status: 200
}
    
export type listMatchesResponseSuccess = (listMatchesResponse200) & {
  headers: Headers;
};
;

export type listMatchesResponse = (listMatchesResponseSuccess)

export const getListMatchesUrl = (params?: ListMatchesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches?${stringifiedParams}` : `/api/v1/matches`
}

export const listMatches = async (params?: ListMatchesParams, options?: RequestInit): Promise<listMatchesResponse> => {
  
  return customInstance<listMatchesResponse>(getListMatchesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListMatchesQueryKey = (params?: ListMatchesParams,) => {
    return [
    `/api/v1/matches`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListMatchesQueryOptions = <TData = Awaited<ReturnType<typeof listMatches>>, TError = unknown>(params?: ListMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMatchesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMatches>>> = ({ signal }) => listMatches(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof listMatches>>>
export type ListMatchesQueryError = unknown


export function useListMatches<TData = Awaited<ReturnType<typeof listMatches>>, TError = unknown>(
 params: undefined |  ListMatchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatches>>,
          TError,
          Awaited<ReturnType<typeof listMatches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatches<TData = Awaited<ReturnType<typeof listMatches>>, TError = unknown>(
 params?: ListMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMatches>>,
          TError,
          Awaited<ReturnType<typeof listMatches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMatches<TData = Awaited<ReturnType<typeof listMatches>>, TError = unknown>(
 params?: ListMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List matches with filters
 */

export function useListMatches<TData = Awaited<ReturnType<typeof listMatches>>, TError = unknown>(
 params?: ListMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMatchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get upcoming matches
 */
export type getUpcomingMatchesResponse200 = {
  data: MatchListResponse
  status: 200
}
    
export type getUpcomingMatchesResponseSuccess = (getUpcomingMatchesResponse200) & {
  headers: Headers;
};
;

export type getUpcomingMatchesResponse = (getUpcomingMatchesResponseSuccess)

export const getGetUpcomingMatchesUrl = (params?: GetUpcomingMatchesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches/upcoming?${stringifiedParams}` : `/api/v1/matches/upcoming`
}

export const getUpcomingMatches = async (params?: GetUpcomingMatchesParams, options?: RequestInit): Promise<getUpcomingMatchesResponse> => {
  
  return customInstance<getUpcomingMatchesResponse>(getGetUpcomingMatchesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUpcomingMatchesQueryKey = (params?: GetUpcomingMatchesParams,) => {
    return [
    `/api/v1/matches/upcoming`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUpcomingMatchesQueryOptions = <TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = unknown>(params?: GetUpcomingMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUpcomingMatchesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUpcomingMatches>>> = ({ signal }) => getUpcomingMatches(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUpcomingMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof getUpcomingMatches>>>
export type GetUpcomingMatchesQueryError = unknown


export function useGetUpcomingMatches<TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = unknown>(
 params: undefined |  GetUpcomingMatchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUpcomingMatches>>,
          TError,
          Awaited<ReturnType<typeof getUpcomingMatches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUpcomingMatches<TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = unknown>(
 params?: GetUpcomingMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUpcomingMatches>>,
          TError,
          Awaited<ReturnType<typeof getUpcomingMatches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUpcomingMatches<TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = unknown>(
 params?: GetUpcomingMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get upcoming matches
 */

export function useGetUpcomingMatches<TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = unknown>(
 params?: GetUpcomingMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUpcomingMatchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get match details
 */
export type getMatchResponse200 = {
  data: Match
  status: 200
}
    
export type getMatchResponseSuccess = (getMatchResponse200) & {
  headers: Headers;
};
;

export type getMatchResponse = (getMatchResponseSuccess)

export const getGetMatchUrl = (matchId: number,) => {


  

  return `/api/v1/matches/${matchId}`
}

export const getMatch = async (matchId: number, options?: RequestInit): Promise<getMatchResponse> => {
  
  return customInstance<getMatchResponse>(getGetMatchUrl(matchId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMatchQueryKey = (matchId: number,) => {
    return [
    `/api/v1/matches/${matchId}`
    ] as const;
    }

    
export const getGetMatchQueryOptions = <TData = Awaited<ReturnType<typeof getMatch>>, TError = unknown>(matchId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMatchQueryKey(matchId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatch>>> = ({ signal }) => getMatch(matchId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(matchId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMatchQueryResult = NonNullable<Awaited<ReturnType<typeof getMatch>>>
export type GetMatchQueryError = unknown


export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = unknown>(
 matchId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatch>>,
          TError,
          Awaited<ReturnType<typeof getMatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = unknown>(
 matchId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatch>>,
          TError,
          Awaited<ReturnType<typeof getMatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = unknown>(
 matchId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get match details
 */

export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = unknown>(
 matchId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMatchQueryOptions(matchId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get head-to-head history
 */
export type getHeadToHeadResponse200 = {
  data: HeadToHeadResponse
  status: 200
}
    
export type getHeadToHeadResponseSuccess = (getHeadToHeadResponse200) & {
  headers: Headers;
};
;

export type getHeadToHeadResponse = (getHeadToHeadResponseSuccess)

export const getGetHeadToHeadUrl = (matchId: number,
    params?: GetHeadToHeadParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches/${matchId}/head-to-head?${stringifiedParams}` : `/api/v1/matches/${matchId}/head-to-head`
}

export const getHeadToHead = async (matchId: number,
    params?: GetHeadToHeadParams, options?: RequestInit): Promise<getHeadToHeadResponse> => {
  
  return customInstance<getHeadToHeadResponse>(getGetHeadToHeadUrl(matchId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetHeadToHeadQueryKey = (matchId: number,
    params?: GetHeadToHeadParams,) => {
    return [
    `/api/v1/matches/${matchId}/head-to-head`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetHeadToHeadQueryOptions = <TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = unknown>(matchId: number,
    params?: GetHeadToHeadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHeadToHeadQueryKey(matchId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHeadToHead>>> = ({ signal }) => getHeadToHead(matchId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(matchId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHeadToHeadQueryResult = NonNullable<Awaited<ReturnType<typeof getHeadToHead>>>
export type GetHeadToHeadQueryError = unknown


export function useGetHeadToHead<TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = unknown>(
 matchId: number,
    params: undefined |  GetHeadToHeadParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeadToHead>>,
          TError,
          Awaited<ReturnType<typeof getHeadToHead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHeadToHead<TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = unknown>(
 matchId: number,
    params?: GetHeadToHeadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeadToHead>>,
          TError,
          Awaited<ReturnType<typeof getHeadToHead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHeadToHead<TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = unknown>(
 matchId: number,
    params?: GetHeadToHeadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get head-to-head history
 */

export function useGetHeadToHead<TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = unknown>(
 matchId: number,
    params?: GetHeadToHeadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHeadToHeadQueryOptions(matchId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get team recent form
 */
export type getTeamFormResponse200 = {
  data: TeamFormResponse
  status: 200
}
    
export type getTeamFormResponseSuccess = (getTeamFormResponse200) & {
  headers: Headers;
};
;

export type getTeamFormResponse = (getTeamFormResponseSuccess)

export const getGetTeamFormUrl = (teamId: number,
    params?: GetTeamFormParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches/teams/${teamId}/form?${stringifiedParams}` : `/api/v1/matches/teams/${teamId}/form`
}

export const getTeamForm = async (teamId: number,
    params?: GetTeamFormParams, options?: RequestInit): Promise<getTeamFormResponse> => {
  
  return customInstance<getTeamFormResponse>(getGetTeamFormUrl(teamId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTeamFormQueryKey = (teamId: number,
    params?: GetTeamFormParams,) => {
    return [
    `/api/v1/matches/teams/${teamId}/form`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetTeamFormQueryOptions = <TData = Awaited<ReturnType<typeof getTeamForm>>, TError = unknown>(teamId: number,
    params?: GetTeamFormParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTeamFormQueryKey(teamId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeamForm>>> = ({ signal }) => getTeamForm(teamId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTeamFormQueryResult = NonNullable<Awaited<ReturnType<typeof getTeamForm>>>
export type GetTeamFormQueryError = unknown


export function useGetTeamForm<TData = Awaited<ReturnType<typeof getTeamForm>>, TError = unknown>(
 teamId: number,
    params: undefined |  GetTeamFormParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamForm>>,
          TError,
          Awaited<ReturnType<typeof getTeamForm>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeamForm<TData = Awaited<ReturnType<typeof getTeamForm>>, TError = unknown>(
 teamId: number,
    params?: GetTeamFormParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamForm>>,
          TError,
          Awaited<ReturnType<typeof getTeamForm>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeamForm<TData = Awaited<ReturnType<typeof getTeamForm>>, TError = unknown>(
 teamId: number,
    params?: GetTeamFormParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get team recent form
 */

export function useGetTeamForm<TData = Awaited<ReturnType<typeof getTeamForm>>, TError = unknown>(
 teamId: number,
    params?: GetTeamFormParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeamFormQueryOptions(teamId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get league standings
 */
export type getStandingsResponse200 = {
  data: StandingsResponse
  status: 200
}
    
export type getStandingsResponseSuccess = (getStandingsResponse200) & {
  headers: Headers;
};
;

export type getStandingsResponse = (getStandingsResponseSuccess)

export const getGetStandingsUrl = (competitionCode: string,) => {


  

  return `/api/v1/matches/standings/${competitionCode}`
}

export const getStandings = async (competitionCode: string, options?: RequestInit): Promise<getStandingsResponse> => {
  
  return customInstance<getStandingsResponse>(getGetStandingsUrl(competitionCode),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStandingsQueryKey = (competitionCode: string,) => {
    return [
    `/api/v1/matches/standings/${competitionCode}`
    ] as const;
    }

    
export const getGetStandingsQueryOptions = <TData = Awaited<ReturnType<typeof getStandings>>, TError = unknown>(competitionCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStandingsQueryKey(competitionCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStandings>>> = ({ signal }) => getStandings(competitionCode, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(competitionCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStandingsQueryResult = NonNullable<Awaited<ReturnType<typeof getStandings>>>
export type GetStandingsQueryError = unknown


export function useGetStandings<TData = Awaited<ReturnType<typeof getStandings>>, TError = unknown>(
 competitionCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStandings>>,
          TError,
          Awaited<ReturnType<typeof getStandings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStandings<TData = Awaited<ReturnType<typeof getStandings>>, TError = unknown>(
 competitionCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStandings>>,
          TError,
          Awaited<ReturnType<typeof getStandings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStandings<TData = Awaited<ReturnType<typeof getStandings>>, TError = unknown>(
 competitionCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get league standings
 */

export function useGetStandings<TData = Awaited<ReturnType<typeof getStandings>>, TError = unknown>(
 competitionCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStandingsQueryOptions(competitionCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




