/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompetitionsListResponse,
  GetHeadToHeadParams,
  GetLiveScoresParams,
  GetMatchesParams,
  GetTeamFormParams,
  GetUpcomingMatchesParams,
  HTTPErrorResponse,
  HTTPValidationError,
  HeadToHeadResponse,
  LiveScoresResponse,
  MatchListResponse,
  MatchResponse,
  StandingsResponse,
  TeamFormResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get list of matches with optional filters from database.

Competition codes:
- PL: Premier League
- PD: La Liga
- BL1: Bundesliga
- SA: Serie A
- FL1: Ligue 1
- CL: Champions League
- EL: Europa League
 * @summary Get Matches
 */
export type getMatchesResponse200 = {
  data: MatchListResponse
  status: 200
}

export type getMatchesResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getMatchesResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getMatchesResponseSuccess = (getMatchesResponse200) & {
  headers: Headers;
};
export type getMatchesResponseError = (getMatchesResponse401 | getMatchesResponse422) & {
  headers: Headers;
};

export type getMatchesResponse = (getMatchesResponseSuccess | getMatchesResponseError)

export const getGetMatchesUrl = (params?: GetMatchesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches?${stringifiedParams}` : `/api/v1/matches`
}

export const getMatches = async (params?: GetMatchesParams, options?: RequestInit): Promise<getMatchesResponse> => {
  
  return customInstance<getMatchesResponse>(getGetMatchesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMatchesQueryKey = (params?: GetMatchesParams,) => {
    return [
    `/api/v1/matches`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMatchesQueryOptions = <TData = Awaited<ReturnType<typeof getMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(params?: GetMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMatchesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatches>>> = ({ signal }) => getMatches(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMatches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof getMatches>>>
export type GetMatchesQueryError = HTTPErrorResponse | HTTPValidationError


export function useGetMatches<TData = Awaited<ReturnType<typeof getMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params: undefined |  GetMatchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatches>>,
          TError,
          Awaited<ReturnType<typeof getMatches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMatches<TData = Awaited<ReturnType<typeof getMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatches>>,
          TError,
          Awaited<ReturnType<typeof getMatches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMatches<TData = Awaited<ReturnType<typeof getMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Matches
 */

export function useGetMatches<TData = Awaited<ReturnType<typeof getMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMatchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get upcoming matches for the next N days from database.
 * @summary Get Upcoming Matches
 */
export type getUpcomingMatchesResponse200 = {
  data: MatchListResponse
  status: 200
}

export type getUpcomingMatchesResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getUpcomingMatchesResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getUpcomingMatchesResponseSuccess = (getUpcomingMatchesResponse200) & {
  headers: Headers;
};
export type getUpcomingMatchesResponseError = (getUpcomingMatchesResponse401 | getUpcomingMatchesResponse422) & {
  headers: Headers;
};

export type getUpcomingMatchesResponse = (getUpcomingMatchesResponseSuccess | getUpcomingMatchesResponseError)

export const getGetUpcomingMatchesUrl = (params?: GetUpcomingMatchesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches/upcoming?${stringifiedParams}` : `/api/v1/matches/upcoming`
}

export const getUpcomingMatches = async (params?: GetUpcomingMatchesParams, options?: RequestInit): Promise<getUpcomingMatchesResponse> => {
  
  return customInstance<getUpcomingMatchesResponse>(getGetUpcomingMatchesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUpcomingMatchesQueryKey = (params?: GetUpcomingMatchesParams,) => {
    return [
    `/api/v1/matches/upcoming`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUpcomingMatchesQueryOptions = <TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(params?: GetUpcomingMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUpcomingMatchesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUpcomingMatches>>> = ({ signal }) => getUpcomingMatches(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUpcomingMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof getUpcomingMatches>>>
export type GetUpcomingMatchesQueryError = HTTPErrorResponse | HTTPValidationError


export function useGetUpcomingMatches<TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params: undefined |  GetUpcomingMatchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUpcomingMatches>>,
          TError,
          Awaited<ReturnType<typeof getUpcomingMatches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUpcomingMatches<TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetUpcomingMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUpcomingMatches>>,
          TError,
          Awaited<ReturnType<typeof getUpcomingMatches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUpcomingMatches<TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetUpcomingMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Upcoming Matches
 */

export function useGetUpcomingMatches<TData = Awaited<ReturnType<typeof getUpcomingMatches>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetUpcomingMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingMatches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUpcomingMatchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get live match scores with real-time updates.

Returns all currently playing matches with scores, minute, and status.
Results are cached for 30 seconds to reduce API calls.
 * @summary Get Live Scores
 */
export type getLiveScoresResponse200 = {
  data: LiveScoresResponse
  status: 200
}

export type getLiveScoresResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getLiveScoresResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getLiveScoresResponseSuccess = (getLiveScoresResponse200) & {
  headers: Headers;
};
export type getLiveScoresResponseError = (getLiveScoresResponse401 | getLiveScoresResponse422) & {
  headers: Headers;
};

export type getLiveScoresResponse = (getLiveScoresResponseSuccess | getLiveScoresResponseError)

export const getGetLiveScoresUrl = (params?: GetLiveScoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches/live?${stringifiedParams}` : `/api/v1/matches/live`
}

export const getLiveScores = async (params?: GetLiveScoresParams, options?: RequestInit): Promise<getLiveScoresResponse> => {
  
  return customInstance<getLiveScoresResponse>(getGetLiveScoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetLiveScoresQueryKey = (params?: GetLiveScoresParams,) => {
    return [
    `/api/v1/matches/live`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetLiveScoresQueryOptions = <TData = Awaited<ReturnType<typeof getLiveScores>>, TError = HTTPErrorResponse | HTTPValidationError>(params?: GetLiveScoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveScores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLiveScoresQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveScores>>> = ({ signal }) => getLiveScores(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiveScores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLiveScoresQueryResult = NonNullable<Awaited<ReturnType<typeof getLiveScores>>>
export type GetLiveScoresQueryError = HTTPErrorResponse | HTTPValidationError


export function useGetLiveScores<TData = Awaited<ReturnType<typeof getLiveScores>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params: undefined |  GetLiveScoresParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveScores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveScores>>,
          TError,
          Awaited<ReturnType<typeof getLiveScores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveScores<TData = Awaited<ReturnType<typeof getLiveScores>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetLiveScoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveScores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveScores>>,
          TError,
          Awaited<ReturnType<typeof getLiveScores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveScores<TData = Awaited<ReturnType<typeof getLiveScores>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetLiveScoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveScores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Live Scores
 */

export function useGetLiveScores<TData = Awaited<ReturnType<typeof getLiveScores>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: GetLiveScoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveScores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLiveScoresQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get list of all supported competitions.

Returns competition codes, names, countries, and flag codes for UI display.
This is the single source of truth for competition data.
 * @summary Get Competitions
 */
export type getCompetitionsResponse200 = {
  data: CompetitionsListResponse
  status: 200
}

export type getCompetitionsResponse401 = {
  data: HTTPErrorResponse
  status: 401
}
    
export type getCompetitionsResponseSuccess = (getCompetitionsResponse200) & {
  headers: Headers;
};
export type getCompetitionsResponseError = (getCompetitionsResponse401) & {
  headers: Headers;
};

export type getCompetitionsResponse = (getCompetitionsResponseSuccess | getCompetitionsResponseError)

export const getGetCompetitionsUrl = () => {


  

  return `/api/v1/matches/competitions`
}

export const getCompetitions = async ( options?: RequestInit): Promise<getCompetitionsResponse> => {
  
  return customInstance<getCompetitionsResponse>(getGetCompetitionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCompetitionsQueryKey = () => {
    return [
    `/api/v1/matches/competitions`
    ] as const;
    }

    
export const getGetCompetitionsQueryOptions = <TData = Awaited<ReturnType<typeof getCompetitions>>, TError = HTTPErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompetitionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompetitions>>> = ({ signal }) => getCompetitions({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompetitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompetitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getCompetitions>>>
export type GetCompetitionsQueryError = HTTPErrorResponse


export function useGetCompetitions<TData = Awaited<ReturnType<typeof getCompetitions>>, TError = HTTPErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompetitions>>,
          TError,
          Awaited<ReturnType<typeof getCompetitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompetitions<TData = Awaited<ReturnType<typeof getCompetitions>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompetitions>>,
          TError,
          Awaited<ReturnType<typeof getCompetitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompetitions<TData = Awaited<ReturnType<typeof getCompetitions>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Competitions
 */

export function useGetCompetitions<TData = Awaited<ReturnType<typeof getCompetitions>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompetitionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get details for a specific match from database (requires authentication).
 * @summary Get Match
 */
export type getMatchResponse200 = {
  data: MatchResponse
  status: 200
}

export type getMatchResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getMatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getMatchResponseSuccess = (getMatchResponse200) & {
  headers: Headers;
};
export type getMatchResponseError = (getMatchResponse401 | getMatchResponse422) & {
  headers: Headers;
};

export type getMatchResponse = (getMatchResponseSuccess | getMatchResponseError)

export const getGetMatchUrl = (matchId: number,) => {


  

  return `/api/v1/matches/${matchId}`
}

export const getMatch = async (matchId: number, options?: RequestInit): Promise<getMatchResponse> => {
  
  return customInstance<getMatchResponse>(getGetMatchUrl(matchId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMatchQueryKey = (matchId: number,) => {
    return [
    `/api/v1/matches/${matchId}`
    ] as const;
    }

    
export const getGetMatchQueryOptions = <TData = Awaited<ReturnType<typeof getMatch>>, TError = HTTPErrorResponse | HTTPValidationError>(matchId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMatchQueryKey(matchId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatch>>> = ({ signal }) => getMatch(matchId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(matchId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMatchQueryResult = NonNullable<Awaited<ReturnType<typeof getMatch>>>
export type GetMatchQueryError = HTTPErrorResponse | HTTPValidationError


export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = HTTPErrorResponse | HTTPValidationError>(
 matchId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatch>>,
          TError,
          Awaited<ReturnType<typeof getMatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = HTTPErrorResponse | HTTPValidationError>(
 matchId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatch>>,
          TError,
          Awaited<ReturnType<typeof getMatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = HTTPErrorResponse | HTTPValidationError>(
 matchId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Match
 */

export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = HTTPErrorResponse | HTTPValidationError>(
 matchId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMatchQueryOptions(matchId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get head-to-head history for teams in a match from database.
 * @summary Get Head To Head
 */
export type getHeadToHeadResponse200 = {
  data: HeadToHeadResponse
  status: 200
}

export type getHeadToHeadResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getHeadToHeadResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getHeadToHeadResponseSuccess = (getHeadToHeadResponse200) & {
  headers: Headers;
};
export type getHeadToHeadResponseError = (getHeadToHeadResponse401 | getHeadToHeadResponse422) & {
  headers: Headers;
};

export type getHeadToHeadResponse = (getHeadToHeadResponseSuccess | getHeadToHeadResponseError)

export const getGetHeadToHeadUrl = (matchId: number,
    params?: GetHeadToHeadParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches/${matchId}/head-to-head?${stringifiedParams}` : `/api/v1/matches/${matchId}/head-to-head`
}

export const getHeadToHead = async (matchId: number,
    params?: GetHeadToHeadParams, options?: RequestInit): Promise<getHeadToHeadResponse> => {
  
  return customInstance<getHeadToHeadResponse>(getGetHeadToHeadUrl(matchId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetHeadToHeadQueryKey = (matchId: number,
    params?: GetHeadToHeadParams,) => {
    return [
    `/api/v1/matches/${matchId}/head-to-head`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetHeadToHeadQueryOptions = <TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = HTTPErrorResponse | HTTPValidationError>(matchId: number,
    params?: GetHeadToHeadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHeadToHeadQueryKey(matchId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHeadToHead>>> = ({ signal }) => getHeadToHead(matchId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(matchId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHeadToHeadQueryResult = NonNullable<Awaited<ReturnType<typeof getHeadToHead>>>
export type GetHeadToHeadQueryError = HTTPErrorResponse | HTTPValidationError


export function useGetHeadToHead<TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = HTTPErrorResponse | HTTPValidationError>(
 matchId: number,
    params: undefined |  GetHeadToHeadParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeadToHead>>,
          TError,
          Awaited<ReturnType<typeof getHeadToHead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHeadToHead<TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = HTTPErrorResponse | HTTPValidationError>(
 matchId: number,
    params?: GetHeadToHeadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeadToHead>>,
          TError,
          Awaited<ReturnType<typeof getHeadToHead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHeadToHead<TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = HTTPErrorResponse | HTTPValidationError>(
 matchId: number,
    params?: GetHeadToHeadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Head To Head
 */

export function useGetHeadToHead<TData = Awaited<ReturnType<typeof getHeadToHead>>, TError = HTTPErrorResponse | HTTPValidationError>(
 matchId: number,
    params?: GetHeadToHeadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeadToHead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHeadToHeadQueryOptions(matchId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get recent form for a team.
 * @summary Get Team Form
 */
export type getTeamFormResponse200 = {
  data: TeamFormResponse
  status: 200
}

export type getTeamFormResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getTeamFormResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getTeamFormResponseSuccess = (getTeamFormResponse200) & {
  headers: Headers;
};
export type getTeamFormResponseError = (getTeamFormResponse401 | getTeamFormResponse422) & {
  headers: Headers;
};

export type getTeamFormResponse = (getTeamFormResponseSuccess | getTeamFormResponseError)

export const getGetTeamFormUrl = (teamId: number,
    params?: GetTeamFormParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/matches/teams/${teamId}/form?${stringifiedParams}` : `/api/v1/matches/teams/${teamId}/form`
}

export const getTeamForm = async (teamId: number,
    params?: GetTeamFormParams, options?: RequestInit): Promise<getTeamFormResponse> => {
  
  return customInstance<getTeamFormResponse>(getGetTeamFormUrl(teamId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTeamFormQueryKey = (teamId: number,
    params?: GetTeamFormParams,) => {
    return [
    `/api/v1/matches/teams/${teamId}/form`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetTeamFormQueryOptions = <TData = Awaited<ReturnType<typeof getTeamForm>>, TError = HTTPErrorResponse | HTTPValidationError>(teamId: number,
    params?: GetTeamFormParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTeamFormQueryKey(teamId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeamForm>>> = ({ signal }) => getTeamForm(teamId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTeamFormQueryResult = NonNullable<Awaited<ReturnType<typeof getTeamForm>>>
export type GetTeamFormQueryError = HTTPErrorResponse | HTTPValidationError


export function useGetTeamForm<TData = Awaited<ReturnType<typeof getTeamForm>>, TError = HTTPErrorResponse | HTTPValidationError>(
 teamId: number,
    params: undefined |  GetTeamFormParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamForm>>,
          TError,
          Awaited<ReturnType<typeof getTeamForm>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeamForm<TData = Awaited<ReturnType<typeof getTeamForm>>, TError = HTTPErrorResponse | HTTPValidationError>(
 teamId: number,
    params?: GetTeamFormParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamForm>>,
          TError,
          Awaited<ReturnType<typeof getTeamForm>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeamForm<TData = Awaited<ReturnType<typeof getTeamForm>>, TError = HTTPErrorResponse | HTTPValidationError>(
 teamId: number,
    params?: GetTeamFormParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Team Form
 */

export function useGetTeamForm<TData = Awaited<ReturnType<typeof getTeamForm>>, TError = HTTPErrorResponse | HTTPValidationError>(
 teamId: number,
    params?: GetTeamFormParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamForm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeamFormQueryOptions(teamId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get current league standings for a competition.

Standings are pre-calculated daily at 6am and cached.

Competition codes:
- PL: Premier League
- PD: La Liga
- BL1: Bundesliga
- SA: Serie A
- FL1: Ligue 1
 * @summary Get Standings
 */
export type getStandingsResponse200 = {
  data: StandingsResponse
  status: 200
}

export type getStandingsResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getStandingsResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getStandingsResponseSuccess = (getStandingsResponse200) & {
  headers: Headers;
};
export type getStandingsResponseError = (getStandingsResponse401 | getStandingsResponse422) & {
  headers: Headers;
};

export type getStandingsResponse = (getStandingsResponseSuccess | getStandingsResponseError)

export const getGetStandingsUrl = (competitionCode: string,) => {


  

  return `/api/v1/matches/standings/${competitionCode}`
}

export const getStandings = async (competitionCode: string, options?: RequestInit): Promise<getStandingsResponse> => {
  
  return customInstance<getStandingsResponse>(getGetStandingsUrl(competitionCode),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStandingsQueryKey = (competitionCode: string,) => {
    return [
    `/api/v1/matches/standings/${competitionCode}`
    ] as const;
    }

    
export const getGetStandingsQueryOptions = <TData = Awaited<ReturnType<typeof getStandings>>, TError = HTTPErrorResponse | HTTPValidationError>(competitionCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStandingsQueryKey(competitionCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStandings>>> = ({ signal }) => getStandings(competitionCode, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(competitionCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStandingsQueryResult = NonNullable<Awaited<ReturnType<typeof getStandings>>>
export type GetStandingsQueryError = HTTPErrorResponse | HTTPValidationError


export function useGetStandings<TData = Awaited<ReturnType<typeof getStandings>>, TError = HTTPErrorResponse | HTTPValidationError>(
 competitionCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStandings>>,
          TError,
          Awaited<ReturnType<typeof getStandings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStandings<TData = Awaited<ReturnType<typeof getStandings>>, TError = HTTPErrorResponse | HTTPValidationError>(
 competitionCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStandings>>,
          TError,
          Awaited<ReturnType<typeof getStandings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStandings<TData = Awaited<ReturnType<typeof getStandings>>, TError = HTTPErrorResponse | HTTPValidationError>(
 competitionCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Standings
 */

export function useGetStandings<TData = Awaited<ReturnType<typeof getStandings>>, TError = HTTPErrorResponse | HTTPValidationError>(
 competitionCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStandings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStandingsQueryOptions(competitionCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




