/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DebugApiStatus200
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Debug endpoint to verify football-data.org API configuration
 */
export type debugApiStatusResponse200 = {
  data: DebugApiStatus200
  status: 200
}
    
export type debugApiStatusResponseSuccess = (debugApiStatusResponse200) & {
  headers: Headers;
};
;

export type debugApiStatusResponse = (debugApiStatusResponseSuccess)

export const getDebugApiStatusUrl = () => {


  

  return `/api/v1/debug/api-status`
}

export const debugApiStatus = async ( options?: RequestInit): Promise<debugApiStatusResponse> => {
  
  return customInstance<debugApiStatusResponse>(getDebugApiStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getDebugApiStatusQueryKey = () => {
    return [
    `/api/v1/debug/api-status`
    ] as const;
    }

    
export const getDebugApiStatusQueryOptions = <TData = Awaited<ReturnType<typeof debugApiStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugApiStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDebugApiStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof debugApiStatus>>> = ({ signal }) => debugApiStatus({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof debugApiStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DebugApiStatusQueryResult = NonNullable<Awaited<ReturnType<typeof debugApiStatus>>>
export type DebugApiStatusQueryError = unknown


export function useDebugApiStatus<TData = Awaited<ReturnType<typeof debugApiStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugApiStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof debugApiStatus>>,
          TError,
          Awaited<ReturnType<typeof debugApiStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDebugApiStatus<TData = Awaited<ReturnType<typeof debugApiStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugApiStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof debugApiStatus>>,
          TError,
          Awaited<ReturnType<typeof debugApiStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDebugApiStatus<TData = Awaited<ReturnType<typeof debugApiStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugApiStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Debug endpoint to verify football-data.org API configuration
 */

export function useDebugApiStatus<TData = Awaited<ReturnType<typeof debugApiStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugApiStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDebugApiStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




