/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AnalyzeMatchContext200,
  AnalyzeMatchContextParams,
  EnrichMatchParams,
  MatchContext,
  RAGStatusResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get RAG system status
 */
export type getRagStatusResponse200 = {
  data: RAGStatusResponse
  status: 200
}
    
export type getRagStatusResponseSuccess = (getRagStatusResponse200) & {
  headers: Headers;
};
;

export type getRagStatusResponse = (getRagStatusResponseSuccess)

export const getGetRagStatusUrl = () => {


  

  return `/api/v1/rag/status`
}

export const getRagStatus = async ( options?: RequestInit): Promise<getRagStatusResponse> => {
  
  return customInstance<getRagStatusResponse>(getGetRagStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetRagStatusQueryKey = () => {
    return [
    `/api/v1/rag/status`
    ] as const;
    }

    
export const getGetRagStatusQueryOptions = <TData = Awaited<ReturnType<typeof getRagStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRagStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRagStatus>>> = ({ signal }) => getRagStatus({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRagStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRagStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getRagStatus>>>
export type GetRagStatusQueryError = unknown


export function useGetRagStatus<TData = Awaited<ReturnType<typeof getRagStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRagStatus>>,
          TError,
          Awaited<ReturnType<typeof getRagStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRagStatus<TData = Awaited<ReturnType<typeof getRagStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRagStatus>>,
          TError,
          Awaited<ReturnType<typeof getRagStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRagStatus<TData = Awaited<ReturnType<typeof getRagStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get RAG system status
 */

export function useGetRagStatus<TData = Awaited<ReturnType<typeof getRagStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRagStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Enrich a match with contextual information using RAG
 */
export type enrichMatchResponse200 = {
  data: MatchContext
  status: 200
}

export type enrichMatchResponse500 = {
  data: void
  status: 500
}
    
export type enrichMatchResponseSuccess = (enrichMatchResponse200) & {
  headers: Headers;
};
export type enrichMatchResponseError = (enrichMatchResponse500) & {
  headers: Headers;
};

export type enrichMatchResponse = (enrichMatchResponseSuccess | enrichMatchResponseError)

export const getEnrichMatchUrl = (params: EnrichMatchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/rag/enrich?${stringifiedParams}` : `/api/v1/rag/enrich`
}

export const enrichMatch = async (params: EnrichMatchParams, options?: RequestInit): Promise<enrichMatchResponse> => {
  
  return customInstance<enrichMatchResponse>(getEnrichMatchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEnrichMatchQueryKey = (params?: EnrichMatchParams,) => {
    return [
    `/api/v1/rag/enrich`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getEnrichMatchQueryOptions = <TData = Awaited<ReturnType<typeof enrichMatch>>, TError = void>(params: EnrichMatchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEnrichMatchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof enrichMatch>>> = ({ signal }) => enrichMatch(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof enrichMatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EnrichMatchQueryResult = NonNullable<Awaited<ReturnType<typeof enrichMatch>>>
export type EnrichMatchQueryError = void


export function useEnrichMatch<TData = Awaited<ReturnType<typeof enrichMatch>>, TError = void>(
 params: EnrichMatchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof enrichMatch>>,
          TError,
          Awaited<ReturnType<typeof enrichMatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnrichMatch<TData = Awaited<ReturnType<typeof enrichMatch>>, TError = void>(
 params: EnrichMatchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof enrichMatch>>,
          TError,
          Awaited<ReturnType<typeof enrichMatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnrichMatch<TData = Awaited<ReturnType<typeof enrichMatch>>, TError = void>(
 params: EnrichMatchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Enrich a match with contextual information using RAG
 */

export function useEnrichMatch<TData = Awaited<ReturnType<typeof enrichMatch>>, TError = void>(
 params: EnrichMatchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEnrichMatchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Generate a detailed analysis of match context using LLM
 */
export type analyzeMatchContextResponse200 = {
  data: AnalyzeMatchContext200
  status: 200
}

export type analyzeMatchContextResponse500 = {
  data: void
  status: 500
}
    
export type analyzeMatchContextResponseSuccess = (analyzeMatchContextResponse200) & {
  headers: Headers;
};
export type analyzeMatchContextResponseError = (analyzeMatchContextResponse500) & {
  headers: Headers;
};

export type analyzeMatchContextResponse = (analyzeMatchContextResponseSuccess | analyzeMatchContextResponseError)

export const getAnalyzeMatchContextUrl = (params: AnalyzeMatchContextParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/rag/analyze?${stringifiedParams}` : `/api/v1/rag/analyze`
}

export const analyzeMatchContext = async (params: AnalyzeMatchContextParams, options?: RequestInit): Promise<analyzeMatchContextResponse> => {
  
  return customInstance<analyzeMatchContextResponse>(getAnalyzeMatchContextUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getAnalyzeMatchContextMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeMatchContext>>, TError,{params: AnalyzeMatchContextParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof analyzeMatchContext>>, TError,{params: AnalyzeMatchContextParams}, TContext> => {

const mutationKey = ['analyzeMatchContext'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof analyzeMatchContext>>, {params: AnalyzeMatchContextParams}> = (props) => {
          const {params} = props ?? {};

          return  analyzeMatchContext(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AnalyzeMatchContextMutationResult = NonNullable<Awaited<ReturnType<typeof analyzeMatchContext>>>
    
    export type AnalyzeMatchContextMutationError = void

    /**
 * @summary Generate a detailed analysis of match context using LLM
 */
export const useAnalyzeMatchContext = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeMatchContext>>, TError,{params: AnalyzeMatchContextParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof analyzeMatchContext>>,
        TError,
        {params: AnalyzeMatchContextParams},
        TContext
      > => {
      return useMutation(getAnalyzeMatchContextMutationOptions(options), queryClient);
    }
    