/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AnalyzeMatchContextApiV1RagAnalyzePost200,
  AnalyzeMatchContextApiV1RagAnalyzePostParams,
  EnrichMatchApiV1RagEnrichGetParams,
  HTTPErrorResponse,
  HTTPValidationError,
  MatchContext,
  RAGStatusResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get RAG system status.
 * @summary Get Rag Status
 */
export type getRagStatusApiV1RagStatusGetResponse200 = {
  data: RAGStatusResponse
  status: 200
}

export type getRagStatusApiV1RagStatusGetResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getRagStatusApiV1RagStatusGetResponse403 = {
  data: HTTPErrorResponse
  status: 403
}
    
export type getRagStatusApiV1RagStatusGetResponseSuccess = (getRagStatusApiV1RagStatusGetResponse200) & {
  headers: Headers;
};
export type getRagStatusApiV1RagStatusGetResponseError = (getRagStatusApiV1RagStatusGetResponse401 | getRagStatusApiV1RagStatusGetResponse403) & {
  headers: Headers;
};

export type getRagStatusApiV1RagStatusGetResponse = (getRagStatusApiV1RagStatusGetResponseSuccess | getRagStatusApiV1RagStatusGetResponseError)

export const getGetRagStatusApiV1RagStatusGetUrl = () => {


  

  return `/api/v1/rag/status`
}

export const getRagStatusApiV1RagStatusGet = async ( options?: RequestInit): Promise<getRagStatusApiV1RagStatusGetResponse> => {
  
  return customInstance<getRagStatusApiV1RagStatusGetResponse>(getGetRagStatusApiV1RagStatusGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetRagStatusApiV1RagStatusGetQueryKey = () => {
    return [
    `/api/v1/rag/status`
    ] as const;
    }

    
export const getGetRagStatusApiV1RagStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError = HTTPErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRagStatusApiV1RagStatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>> = ({ signal }) => getRagStatusApiV1RagStatusGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRagStatusApiV1RagStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>>
export type GetRagStatusApiV1RagStatusGetQueryError = HTTPErrorResponse


export function useGetRagStatusApiV1RagStatusGet<TData = Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError = HTTPErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRagStatusApiV1RagStatusGet<TData = Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRagStatusApiV1RagStatusGet<TData = Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Rag Status
 */

export function useGetRagStatusApiV1RagStatusGet<TData = Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRagStatusApiV1RagStatusGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRagStatusApiV1RagStatusGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Enrich a match with contextual information using RAG.

This endpoint fetches news, injuries, sentiment analysis,
and other contextual data for a match.
 * @summary Enrich Match
 */
export type enrichMatchApiV1RagEnrichGetResponse200 = {
  data: MatchContext
  status: 200
}

export type enrichMatchApiV1RagEnrichGetResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type enrichMatchApiV1RagEnrichGetResponse403 = {
  data: HTTPErrorResponse
  status: 403
}

export type enrichMatchApiV1RagEnrichGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type enrichMatchApiV1RagEnrichGetResponseSuccess = (enrichMatchApiV1RagEnrichGetResponse200) & {
  headers: Headers;
};
export type enrichMatchApiV1RagEnrichGetResponseError = (enrichMatchApiV1RagEnrichGetResponse401 | enrichMatchApiV1RagEnrichGetResponse403 | enrichMatchApiV1RagEnrichGetResponse422) & {
  headers: Headers;
};

export type enrichMatchApiV1RagEnrichGetResponse = (enrichMatchApiV1RagEnrichGetResponseSuccess | enrichMatchApiV1RagEnrichGetResponseError)

export const getEnrichMatchApiV1RagEnrichGetUrl = (params: EnrichMatchApiV1RagEnrichGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/rag/enrich?${stringifiedParams}` : `/api/v1/rag/enrich`
}

export const enrichMatchApiV1RagEnrichGet = async (params: EnrichMatchApiV1RagEnrichGetParams, options?: RequestInit): Promise<enrichMatchApiV1RagEnrichGetResponse> => {
  
  return customInstance<enrichMatchApiV1RagEnrichGetResponse>(getEnrichMatchApiV1RagEnrichGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEnrichMatchApiV1RagEnrichGetQueryKey = (params?: EnrichMatchApiV1RagEnrichGetParams,) => {
    return [
    `/api/v1/rag/enrich`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getEnrichMatchApiV1RagEnrichGetQueryOptions = <TData = Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError = HTTPErrorResponse | HTTPValidationError>(params: EnrichMatchApiV1RagEnrichGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEnrichMatchApiV1RagEnrichGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>> = ({ signal }) => enrichMatchApiV1RagEnrichGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EnrichMatchApiV1RagEnrichGetQueryResult = NonNullable<Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>>
export type EnrichMatchApiV1RagEnrichGetQueryError = HTTPErrorResponse | HTTPValidationError


export function useEnrichMatchApiV1RagEnrichGet<TData = Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params: EnrichMatchApiV1RagEnrichGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>,
          TError,
          Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnrichMatchApiV1RagEnrichGet<TData = Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params: EnrichMatchApiV1RagEnrichGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>,
          TError,
          Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnrichMatchApiV1RagEnrichGet<TData = Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params: EnrichMatchApiV1RagEnrichGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Enrich Match
 */

export function useEnrichMatchApiV1RagEnrichGet<TData = Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params: EnrichMatchApiV1RagEnrichGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enrichMatchApiV1RagEnrichGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEnrichMatchApiV1RagEnrichGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Generate a detailed analysis of match context using LLM.

This is a more intensive analysis than the basic enrichment.
 * @summary Analyze Match Context
 */
export type analyzeMatchContextApiV1RagAnalyzePostResponse200 = {
  data: AnalyzeMatchContextApiV1RagAnalyzePost200
  status: 200
}

export type analyzeMatchContextApiV1RagAnalyzePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type analyzeMatchContextApiV1RagAnalyzePostResponseSuccess = (analyzeMatchContextApiV1RagAnalyzePostResponse200) & {
  headers: Headers;
};
export type analyzeMatchContextApiV1RagAnalyzePostResponseError = (analyzeMatchContextApiV1RagAnalyzePostResponse422) & {
  headers: Headers;
};

export type analyzeMatchContextApiV1RagAnalyzePostResponse = (analyzeMatchContextApiV1RagAnalyzePostResponseSuccess | analyzeMatchContextApiV1RagAnalyzePostResponseError)

export const getAnalyzeMatchContextApiV1RagAnalyzePostUrl = (params: AnalyzeMatchContextApiV1RagAnalyzePostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/rag/analyze?${stringifiedParams}` : `/api/v1/rag/analyze`
}

export const analyzeMatchContextApiV1RagAnalyzePost = async (params: AnalyzeMatchContextApiV1RagAnalyzePostParams, options?: RequestInit): Promise<analyzeMatchContextApiV1RagAnalyzePostResponse> => {
  
  return customInstance<analyzeMatchContextApiV1RagAnalyzePostResponse>(getAnalyzeMatchContextApiV1RagAnalyzePostUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getAnalyzeMatchContextApiV1RagAnalyzePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeMatchContextApiV1RagAnalyzePost>>, TError,{params: AnalyzeMatchContextApiV1RagAnalyzePostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof analyzeMatchContextApiV1RagAnalyzePost>>, TError,{params: AnalyzeMatchContextApiV1RagAnalyzePostParams}, TContext> => {

const mutationKey = ['analyzeMatchContextApiV1RagAnalyzePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof analyzeMatchContextApiV1RagAnalyzePost>>, {params: AnalyzeMatchContextApiV1RagAnalyzePostParams}> = (props) => {
          const {params} = props ?? {};

          return  analyzeMatchContextApiV1RagAnalyzePost(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AnalyzeMatchContextApiV1RagAnalyzePostMutationResult = NonNullable<Awaited<ReturnType<typeof analyzeMatchContextApiV1RagAnalyzePost>>>
    
    export type AnalyzeMatchContextApiV1RagAnalyzePostMutationError = HTTPValidationError

    /**
 * @summary Analyze Match Context
 */
export const useAnalyzeMatchContextApiV1RagAnalyzePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzeMatchContextApiV1RagAnalyzePost>>, TError,{params: AnalyzeMatchContextApiV1RagAnalyzePostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof analyzeMatchContextApiV1RagAnalyzePost>>,
        TError,
        {params: AnalyzeMatchContextApiV1RagAnalyzePostParams},
        TContext
      > => {
      return useMutation(getAnalyzeMatchContextApiV1RagAnalyzePostMutationOptions(options), queryClient);
    }
    