/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DbStatsResponse,
  GetLastSyncInfo200,
  GetLastSyncInfoParams,
  SyncMatchesOnlyParams,
  SyncResponse,
  SyncWeeklyDataParams
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Trigger weekly data synchronization
 */
export type syncWeeklyDataResponse200 = {
  data: SyncResponse
  status: 200
}

export type syncWeeklyDataResponse500 = {
  data: void
  status: 500
}
    
export type syncWeeklyDataResponseSuccess = (syncWeeklyDataResponse200) & {
  headers: Headers;
};
export type syncWeeklyDataResponseError = (syncWeeklyDataResponse500) & {
  headers: Headers;
};

export type syncWeeklyDataResponse = (syncWeeklyDataResponseSuccess | syncWeeklyDataResponseError)

export const getSyncWeeklyDataUrl = (params?: SyncWeeklyDataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sync/weekly?${stringifiedParams}` : `/api/v1/sync/weekly`
}

export const syncWeeklyData = async (params?: SyncWeeklyDataParams, options?: RequestInit): Promise<syncWeeklyDataResponse> => {
  
  return customInstance<syncWeeklyDataResponse>(getSyncWeeklyDataUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getSyncWeeklyDataMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncWeeklyData>>, TError,{params?: SyncWeeklyDataParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof syncWeeklyData>>, TError,{params?: SyncWeeklyDataParams}, TContext> => {

const mutationKey = ['syncWeeklyData'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncWeeklyData>>, {params?: SyncWeeklyDataParams}> = (props) => {
          const {params} = props ?? {};

          return  syncWeeklyData(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SyncWeeklyDataMutationResult = NonNullable<Awaited<ReturnType<typeof syncWeeklyData>>>
    
    export type SyncWeeklyDataMutationError = void

    /**
 * @summary Trigger weekly data synchronization
 */
export const useSyncWeeklyData = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncWeeklyData>>, TError,{params?: SyncWeeklyDataParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncWeeklyData>>,
        TError,
        {params?: SyncWeeklyDataParams},
        TContext
      > => {
      return useMutation(getSyncWeeklyDataMutationOptions(options), queryClient);
    }
    /**
 * @summary Sync only matches (no standings)
 */
export type syncMatchesOnlyResponse200 = {
  data: SyncResponse
  status: 200
}

export type syncMatchesOnlyResponse500 = {
  data: void
  status: 500
}
    
export type syncMatchesOnlyResponseSuccess = (syncMatchesOnlyResponse200) & {
  headers: Headers;
};
export type syncMatchesOnlyResponseError = (syncMatchesOnlyResponse500) & {
  headers: Headers;
};

export type syncMatchesOnlyResponse = (syncMatchesOnlyResponseSuccess | syncMatchesOnlyResponseError)

export const getSyncMatchesOnlyUrl = (params?: SyncMatchesOnlyParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sync/matches?${stringifiedParams}` : `/api/v1/sync/matches`
}

export const syncMatchesOnly = async (params?: SyncMatchesOnlyParams, options?: RequestInit): Promise<syncMatchesOnlyResponse> => {
  
  return customInstance<syncMatchesOnlyResponse>(getSyncMatchesOnlyUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getSyncMatchesOnlyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncMatchesOnly>>, TError,{params?: SyncMatchesOnlyParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof syncMatchesOnly>>, TError,{params?: SyncMatchesOnlyParams}, TContext> => {

const mutationKey = ['syncMatchesOnly'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncMatchesOnly>>, {params?: SyncMatchesOnlyParams}> = (props) => {
          const {params} = props ?? {};

          return  syncMatchesOnly(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SyncMatchesOnlyMutationResult = NonNullable<Awaited<ReturnType<typeof syncMatchesOnly>>>
    
    export type SyncMatchesOnlyMutationError = void

    /**
 * @summary Sync only matches (no standings)
 */
export const useSyncMatchesOnly = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncMatchesOnly>>, TError,{params?: SyncMatchesOnlyParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncMatchesOnly>>,
        TError,
        {params?: SyncMatchesOnlyParams},
        TContext
      > => {
      return useMutation(getSyncMatchesOnlyMutationOptions(options), queryClient);
    }
    /**
 * @summary Sync only standings (no matches)
 */
export type syncStandingsOnlyResponse200 = {
  data: SyncResponse
  status: 200
}

export type syncStandingsOnlyResponse500 = {
  data: void
  status: 500
}
    
export type syncStandingsOnlyResponseSuccess = (syncStandingsOnlyResponse200) & {
  headers: Headers;
};
export type syncStandingsOnlyResponseError = (syncStandingsOnlyResponse500) & {
  headers: Headers;
};

export type syncStandingsOnlyResponse = (syncStandingsOnlyResponseSuccess | syncStandingsOnlyResponseError)

export const getSyncStandingsOnlyUrl = () => {


  

  return `/api/v1/sync/standings`
}

export const syncStandingsOnly = async ( options?: RequestInit): Promise<syncStandingsOnlyResponse> => {
  
  return customInstance<syncStandingsOnlyResponse>(getSyncStandingsOnlyUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getSyncStandingsOnlyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncStandingsOnly>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof syncStandingsOnly>>, TError,void, TContext> => {

const mutationKey = ['syncStandingsOnly'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncStandingsOnly>>, void> = () => {
          

          return  syncStandingsOnly(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SyncStandingsOnlyMutationResult = NonNullable<Awaited<ReturnType<typeof syncStandingsOnly>>>
    
    export type SyncStandingsOnlyMutationError = void

    /**
 * @summary Sync only standings (no matches)
 */
export const useSyncStandingsOnly = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncStandingsOnly>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncStandingsOnly>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncStandingsOnlyMutationOptions(options), queryClient);
    }
    /**
 * @summary Get database sync status and statistics
 */
export type getSyncStatusResponse200 = {
  data: DbStatsResponse
  status: 200
}
    
export type getSyncStatusResponseSuccess = (getSyncStatusResponse200) & {
  headers: Headers;
};
;

export type getSyncStatusResponse = (getSyncStatusResponseSuccess)

export const getGetSyncStatusUrl = () => {


  

  return `/api/v1/sync/status`
}

export const getSyncStatus = async ( options?: RequestInit): Promise<getSyncStatusResponse> => {
  
  return customInstance<getSyncStatusResponse>(getGetSyncStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSyncStatusQueryKey = () => {
    return [
    `/api/v1/sync/status`
    ] as const;
    }

    
export const getGetSyncStatusQueryOptions = <TData = Awaited<ReturnType<typeof getSyncStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSyncStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSyncStatus>>> = ({ signal }) => getSyncStatus({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSyncStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSyncStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getSyncStatus>>>
export type GetSyncStatusQueryError = unknown


export function useGetSyncStatus<TData = Awaited<ReturnType<typeof getSyncStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSyncStatus>>,
          TError,
          Awaited<ReturnType<typeof getSyncStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSyncStatus<TData = Awaited<ReturnType<typeof getSyncStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSyncStatus>>,
          TError,
          Awaited<ReturnType<typeof getSyncStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSyncStatus<TData = Awaited<ReturnType<typeof getSyncStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get database sync status and statistics
 */

export function useGetSyncStatus<TData = Awaited<ReturnType<typeof getSyncStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSyncStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get info about the last successful sync
 */
export type getLastSyncInfoResponse200 = {
  data: GetLastSyncInfo200
  status: 200
}
    
export type getLastSyncInfoResponseSuccess = (getLastSyncInfoResponse200) & {
  headers: Headers;
};
;

export type getLastSyncInfoResponse = (getLastSyncInfoResponseSuccess)

export const getGetLastSyncInfoUrl = (params?: GetLastSyncInfoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sync/last?${stringifiedParams}` : `/api/v1/sync/last`
}

export const getLastSyncInfo = async (params?: GetLastSyncInfoParams, options?: RequestInit): Promise<getLastSyncInfoResponse> => {
  
  return customInstance<getLastSyncInfoResponse>(getGetLastSyncInfoUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetLastSyncInfoQueryKey = (params?: GetLastSyncInfoParams,) => {
    return [
    `/api/v1/sync/last`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetLastSyncInfoQueryOptions = <TData = Awaited<ReturnType<typeof getLastSyncInfo>>, TError = unknown>(params?: GetLastSyncInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastSyncInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLastSyncInfoQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLastSyncInfo>>> = ({ signal }) => getLastSyncInfo(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLastSyncInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLastSyncInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getLastSyncInfo>>>
export type GetLastSyncInfoQueryError = unknown


export function useGetLastSyncInfo<TData = Awaited<ReturnType<typeof getLastSyncInfo>>, TError = unknown>(
 params: undefined |  GetLastSyncInfoParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastSyncInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLastSyncInfo>>,
          TError,
          Awaited<ReturnType<typeof getLastSyncInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLastSyncInfo<TData = Awaited<ReturnType<typeof getLastSyncInfo>>, TError = unknown>(
 params?: GetLastSyncInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastSyncInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLastSyncInfo>>,
          TError,
          Awaited<ReturnType<typeof getLastSyncInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLastSyncInfo<TData = Awaited<ReturnType<typeof getLastSyncInfo>>, TError = unknown>(
 params?: GetLastSyncInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastSyncInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get info about the last successful sync
 */

export function useGetLastSyncInfo<TData = Awaited<ReturnType<typeof getLastSyncInfo>>, TError = unknown>(
 params?: GetLastSyncInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLastSyncInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLastSyncInfoQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




