/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TestimonialListResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get approved testimonials.

Returns up to 6 most recent approved testimonials.
No authentication required (public endpoint).
 * @summary Get Testimonials
 */
export type getTestimonialsApiV1TestimonialsGetResponse200 = {
  data: TestimonialListResponse
  status: 200
}
    
export type getTestimonialsApiV1TestimonialsGetResponseSuccess = (getTestimonialsApiV1TestimonialsGetResponse200) & {
  headers: Headers;
};
;

export type getTestimonialsApiV1TestimonialsGetResponse = (getTestimonialsApiV1TestimonialsGetResponseSuccess)

export const getGetTestimonialsApiV1TestimonialsGetUrl = () => {


  

  return `/api/v1/testimonials`
}

export const getTestimonialsApiV1TestimonialsGet = async ( options?: RequestInit): Promise<getTestimonialsApiV1TestimonialsGetResponse> => {
  
  return customInstance<getTestimonialsApiV1TestimonialsGetResponse>(getGetTestimonialsApiV1TestimonialsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTestimonialsApiV1TestimonialsGetQueryKey = () => {
    return [
    `/api/v1/testimonials`
    ] as const;
    }

    
export const getGetTestimonialsApiV1TestimonialsGetQueryOptions = <TData = Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTestimonialsApiV1TestimonialsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>> = ({ signal }) => getTestimonialsApiV1TestimonialsGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTestimonialsApiV1TestimonialsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>>
export type GetTestimonialsApiV1TestimonialsGetQueryError = unknown


export function useGetTestimonialsApiV1TestimonialsGet<TData = Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>,
          TError,
          Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTestimonialsApiV1TestimonialsGet<TData = Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>,
          TError,
          Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTestimonialsApiV1TestimonialsGet<TData = Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Testimonials
 */

export function useGetTestimonialsApiV1TestimonialsGet<TData = Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTestimonialsApiV1TestimonialsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTestimonialsApiV1TestimonialsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




