/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminStatsResponse,
  HTTPErrorResponse,
  HTTPValidationError,
  ListUsersApiV1AdminUsersGetParams,
  UpdateUserRoleApiV1AdminUsersUserIdRolePost200,
  UpdateUserRoleApiV1AdminUsersUserIdRolePostParams,
  UserListResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get admin dashboard statistics.

Returns platform-wide statistics for the admin dashboard.
Admin role required.
 * @summary Get Admin Stats
 */
export type getAdminStatsApiV1AdminStatsGetResponse200 = {
  data: AdminStatsResponse
  status: 200
}

export type getAdminStatsApiV1AdminStatsGetResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type getAdminStatsApiV1AdminStatsGetResponse403 = {
  data: HTTPErrorResponse
  status: 403
}
    
export type getAdminStatsApiV1AdminStatsGetResponseSuccess = (getAdminStatsApiV1AdminStatsGetResponse200) & {
  headers: Headers;
};
export type getAdminStatsApiV1AdminStatsGetResponseError = (getAdminStatsApiV1AdminStatsGetResponse401 | getAdminStatsApiV1AdminStatsGetResponse403) & {
  headers: Headers;
};

export type getAdminStatsApiV1AdminStatsGetResponse = (getAdminStatsApiV1AdminStatsGetResponseSuccess | getAdminStatsApiV1AdminStatsGetResponseError)

export const getGetAdminStatsApiV1AdminStatsGetUrl = () => {


  

  return `/api/v1/admin/stats`
}

export const getAdminStatsApiV1AdminStatsGet = async ( options?: RequestInit): Promise<getAdminStatsApiV1AdminStatsGetResponse> => {
  
  return customInstance<getAdminStatsApiV1AdminStatsGetResponse>(getGetAdminStatsApiV1AdminStatsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAdminStatsApiV1AdminStatsGetQueryKey = () => {
    return [
    `/api/v1/admin/stats`
    ] as const;
    }

    
export const getGetAdminStatsApiV1AdminStatsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError = HTTPErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminStatsApiV1AdminStatsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>> = ({ signal }) => getAdminStatsApiV1AdminStatsGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminStatsApiV1AdminStatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>>
export type GetAdminStatsApiV1AdminStatsGetQueryError = HTTPErrorResponse


export function useGetAdminStatsApiV1AdminStatsGet<TData = Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError = HTTPErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminStatsApiV1AdminStatsGet<TData = Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminStatsApiV1AdminStatsGet<TData = Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Admin Stats
 */

export function useGetAdminStatsApiV1AdminStatsGet<TData = Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError = HTTPErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStatsApiV1AdminStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminStatsApiV1AdminStatsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * List all users (admin only).

Returns a paginated list of all users.
Admin role required.
 * @summary List Users
 */
export type listUsersApiV1AdminUsersGetResponse200 = {
  data: UserListResponse
  status: 200
}

export type listUsersApiV1AdminUsersGetResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type listUsersApiV1AdminUsersGetResponse403 = {
  data: HTTPErrorResponse
  status: 403
}

export type listUsersApiV1AdminUsersGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type listUsersApiV1AdminUsersGetResponseSuccess = (listUsersApiV1AdminUsersGetResponse200) & {
  headers: Headers;
};
export type listUsersApiV1AdminUsersGetResponseError = (listUsersApiV1AdminUsersGetResponse401 | listUsersApiV1AdminUsersGetResponse403 | listUsersApiV1AdminUsersGetResponse422) & {
  headers: Headers;
};

export type listUsersApiV1AdminUsersGetResponse = (listUsersApiV1AdminUsersGetResponseSuccess | listUsersApiV1AdminUsersGetResponseError)

export const getListUsersApiV1AdminUsersGetUrl = (params?: ListUsersApiV1AdminUsersGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/users?${stringifiedParams}` : `/api/v1/admin/users`
}

export const listUsersApiV1AdminUsersGet = async (params?: ListUsersApiV1AdminUsersGetParams, options?: RequestInit): Promise<listUsersApiV1AdminUsersGetResponse> => {
  
  return customInstance<listUsersApiV1AdminUsersGetResponse>(getListUsersApiV1AdminUsersGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListUsersApiV1AdminUsersGetQueryKey = (params?: ListUsersApiV1AdminUsersGetParams,) => {
    return [
    `/api/v1/admin/users`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListUsersApiV1AdminUsersGetQueryOptions = <TData = Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError = HTTPErrorResponse | HTTPValidationError>(params?: ListUsersApiV1AdminUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersApiV1AdminUsersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>> = ({ signal }) => listUsersApiV1AdminUsersGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersApiV1AdminUsersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>>
export type ListUsersApiV1AdminUsersGetQueryError = HTTPErrorResponse | HTTPValidationError


export function useListUsersApiV1AdminUsersGet<TData = Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params: undefined |  ListUsersApiV1AdminUsersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>,
          TError,
          Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsersApiV1AdminUsersGet<TData = Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: ListUsersApiV1AdminUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>,
          TError,
          Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsersApiV1AdminUsersGet<TData = Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: ListUsersApiV1AdminUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Users
 */

export function useListUsersApiV1AdminUsersGet<TData = Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError = HTTPErrorResponse | HTTPValidationError>(
 params?: ListUsersApiV1AdminUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersApiV1AdminUsersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersApiV1AdminUsersGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a user's role (admin only).

Changes a user's role (free, premium, admin).
Admin role required.
 * @summary Update User Role
 */
export type updateUserRoleApiV1AdminUsersUserIdRolePostResponse200 = {
  data: UpdateUserRoleApiV1AdminUsersUserIdRolePost200
  status: 200
}

export type updateUserRoleApiV1AdminUsersUserIdRolePostResponse401 = {
  data: HTTPErrorResponse
  status: 401
}

export type updateUserRoleApiV1AdminUsersUserIdRolePostResponse403 = {
  data: HTTPErrorResponse
  status: 403
}

export type updateUserRoleApiV1AdminUsersUserIdRolePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateUserRoleApiV1AdminUsersUserIdRolePostResponseSuccess = (updateUserRoleApiV1AdminUsersUserIdRolePostResponse200) & {
  headers: Headers;
};
export type updateUserRoleApiV1AdminUsersUserIdRolePostResponseError = (updateUserRoleApiV1AdminUsersUserIdRolePostResponse401 | updateUserRoleApiV1AdminUsersUserIdRolePostResponse403 | updateUserRoleApiV1AdminUsersUserIdRolePostResponse422) & {
  headers: Headers;
};

export type updateUserRoleApiV1AdminUsersUserIdRolePostResponse = (updateUserRoleApiV1AdminUsersUserIdRolePostResponseSuccess | updateUserRoleApiV1AdminUsersUserIdRolePostResponseError)

export const getUpdateUserRoleApiV1AdminUsersUserIdRolePostUrl = (userId: string,
    params: UpdateUserRoleApiV1AdminUsersUserIdRolePostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/users/${userId}/role?${stringifiedParams}` : `/api/v1/admin/users/${userId}/role`
}

export const updateUserRoleApiV1AdminUsersUserIdRolePost = async (userId: string,
    params: UpdateUserRoleApiV1AdminUsersUserIdRolePostParams, options?: RequestInit): Promise<updateUserRoleApiV1AdminUsersUserIdRolePostResponse> => {
  
  return customInstance<updateUserRoleApiV1AdminUsersUserIdRolePostResponse>(getUpdateUserRoleApiV1AdminUsersUserIdRolePostUrl(userId,params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getUpdateUserRoleApiV1AdminUsersUserIdRolePostMutationOptions = <TError = HTTPErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRoleApiV1AdminUsersUserIdRolePost>>, TError,{userId: string;params: UpdateUserRoleApiV1AdminUsersUserIdRolePostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserRoleApiV1AdminUsersUserIdRolePost>>, TError,{userId: string;params: UpdateUserRoleApiV1AdminUsersUserIdRolePostParams}, TContext> => {

const mutationKey = ['updateUserRoleApiV1AdminUsersUserIdRolePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserRoleApiV1AdminUsersUserIdRolePost>>, {userId: string;params: UpdateUserRoleApiV1AdminUsersUserIdRolePostParams}> = (props) => {
          const {userId,params} = props ?? {};

          return  updateUserRoleApiV1AdminUsersUserIdRolePost(userId,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserRoleApiV1AdminUsersUserIdRolePostMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserRoleApiV1AdminUsersUserIdRolePost>>>
    
    export type UpdateUserRoleApiV1AdminUsersUserIdRolePostMutationError = HTTPErrorResponse | HTTPValidationError

    /**
 * @summary Update User Role
 */
export const useUpdateUserRoleApiV1AdminUsersUserIdRolePost = <TError = HTTPErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRoleApiV1AdminUsersUserIdRolePost>>, TError,{userId: string;params: UpdateUserRoleApiV1AdminUsersUserIdRolePostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserRoleApiV1AdminUsersUserIdRolePost>>,
        TError,
        {userId: string;params: UpdateUserRoleApiV1AdminUsersUserIdRolePostParams},
        TContext
      > => {
      return useMutation(getUpdateUserRoleApiV1AdminUsersUserIdRolePostMutationOptions(options), queryClient);
    }
    