/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Version IDs and their traffic weights (e.g., {'v1': 0.5, 'v2': 0.5})
 */
export type ABTestStartVersionWeights = {[key: string]: number};
