/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { ABTestStartVersionWeights } from './aBTestStartVersionWeights';

/**
 * Request to start an A/B test.
 */
export interface ABTestStart {
  /** Type of prompt to test */
  prompt_type: string;
  /** Version IDs and their traffic weights (e.g., {'v1': 0.5, 'v2': 0.5}) */
  version_weights: ABTestStartVersionWeights;
  /** Test duration in days (None for indefinite) */
  duration_days?: number | null;
}
