/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Admin dashboard statistics.
 */
export interface AdminStatsResponse {
  total_users: number;
  premium_users: number;
  total_predictions: number;
  success_rate: number;
  total_matches: number;
  competitions_with_standings: number;
  last_match_sync: string | null;
  last_standings_sync: string | null;
}
