/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */

export type AnalyzeMatchContextParams = {
home_team: string;
away_team: string;
competition?: string;
additional_context?: string;
};
