/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */

export type AnalyzeMatchParams = {
/**
 * Home team name
 */
home_team: string;
/**
 * Away team name
 */
away_team: string;
/**
 * Competition code
 */
competition?: string;
/**
 * Additional context
 */
additional_context?: string;
};
