/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */

export interface AnalysisResponse {
  home_team: string;
  away_team: string;
  competition: string;
  analysis: string;
  generated_at: string;
}
