/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Bankroll summary response.
 */
export interface BankrollResponse {
  initial_bankroll: number;
  current_bankroll: number;
  total_staked: number;
  total_returned: number;
  profit_loss: number;
  roi_pct: number;
  win_rate: number;
  total_bets: number;
  won_bets: number;
  lost_bets: number;
  pending_bets: number;
  alert_threshold: number;
  is_below_threshold: boolean;
}
