/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * User bankroll settings.
 */
export interface BankrollSettings {
  /**
   * Initial bankroll amount
   * @minimum 0
   */
  initial_bankroll: number;
  /**
   * Alert when bankroll drops below this % of initial
   * @minimum 0
   * @maximum 100
   */
  alert_threshold?: number;
  /**
   * Default stake as % of current bankroll
   * @minimum 0.1
   * @maximum 100
   */
  default_stake_pct?: number;
}
