/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { BasketballTeamResponse } from './basketballTeamResponse';

export interface BasketballMatchResponse {
  id: number;
  home_team: BasketballTeamResponse;
  away_team: BasketballTeamResponse;
  league: string;
  match_date: string;
  status: string;
  home_score?: number | null;
  away_score?: number | null;
  home_q1?: number | null;
  away_q1?: number | null;
  home_q2?: number | null;
  away_q2?: number | null;
  home_q3?: number | null;
  away_q3?: number | null;
  home_q4?: number | null;
  away_q4?: number | null;
  odds_home?: number | null;
  odds_away?: number | null;
  spread?: number | null;
  over_under?: number | null;
  pred_home_prob?: number | null;
  pred_away_prob?: number | null;
  pred_confidence?: number | null;
  pred_explanation?: string | null;
  is_back_to_back_home?: boolean;
  is_back_to_back_away?: boolean;
}
