/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { BasketballTeamResponse } from './basketballTeamResponse';

export interface BasketballStandingEntry {
  team: BasketballTeamResponse;
  wins: number;
  losses: number;
  win_rate?: number | null;
  conference?: string | null;
  division?: string | null;
}
