/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { BasketballStandingEntry } from './basketballStandingEntry';

export interface BasketballStandingsResponse {
  league: string;
  standings: BasketballStandingEntry[];
}
