/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for sports betting
 * OpenAPI spec version: 1.0.0
 */
import type { BetPrediction } from './betPrediction';
import type { BetStatus } from './betStatus';

export interface Bet {
  id: string;
  match_id: string;
  prediction: BetPrediction;
  amount: number;
  odds: number;
  status: BetStatus;
  created_at: string;
}
