/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for sports betting
 * OpenAPI spec version: 1.0.0
 */
import type { BetCreatePrediction } from './betCreatePrediction';

export interface BetCreate {
  match_id: string;
  prediction: BetCreatePrediction;
  amount: number;
}
