/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Create a new bet.
 */
export interface BetCreate {
  match_id: number;
  /** home_win, away_win, or draw */
  prediction: string;
  /**
   * Odds for this bet
   * @minimum 1.01
   */
  odds: number;
  /**
   * Stake amount
   * @minimum 0
   */
  amount: number;
  /** Confidence level % */
  confidence?: number | null;
}
