/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for sports betting
 * OpenAPI spec version: 1.0.0
 */

export type BetPrediction = typeof BetPrediction[keyof typeof BetPrediction];


export const BetPrediction = {
  home_win: 'home_win',
  draw: 'draw',
  away_win: 'away_win',
} as const;
