/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Bet response.
 */
export interface BetResponse {
  id: number;
  match_id: number;
  prediction: string;
  odds: number;
  amount: number;
  status: string;
  potential_return: number;
  actual_return: number | null;
  confidence: number | null;
  created_at: string;
}
