/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Update bet status.
 */
export interface BetUpdate {
  /** pending, won, lost, void */
  status: string;
}
