/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Both Teams To Score response.
 */
export interface BttsResponse {
  /**
   * Probability both teams score
   * @minimum 0
   * @maximum 1
   */
  yes_prob: number;
  /**
   * Probability one team blanks
   * @minimum 0
   * @maximum 1
   */
  no_prob: number;
  /** Fair odds for BTTS Yes */
  yes_odds?: number | null;
  /** Fair odds for BTTS No */
  no_odds?: number | null;
  /** Recommended bet: yes or no */
  recommended?: string;
}
