/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { CorrectScoreResponseScores } from './correctScoreResponseScores';

/**
 * Correct Score prediction response.
 */
export interface CorrectScoreResponse {
  /** Top 6 most likely scores with probabilities */
  scores: CorrectScoreResponseScores;
  /** Most likely score */
  most_likely: string;
  /**
   * Probability of most likely score
   * @minimum 0
   * @maximum 1
   */
  most_likely_prob: number;
}
