/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to index a custom article.
 */
export interface CustomArticleRequest {
  /**
   * @minLength 5
   * @maxLength 500
   */
  title: string;
  content?: string | null;
  team_name?: string | null;
  article_type?: string;
}
