/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { DailyPickResponse } from './dailyPickResponse';
import type { DataSourceInfo } from './dataSourceInfo';

/**
 * Response for daily picks endpoint.
 */
export interface DailyPicksResponse {
  date: string;
  picks: DailyPickResponse[];
  total_matches_analyzed: number;
  data_source?: DataSourceInfo | null;
}
