/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Single day's prediction statistics.
 */
export interface DailyStatsItem {
  date: string;
  predictions: number;
  correct: number;
  accuracy: number;
}
