/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { PredictionResponse } from './predictionResponse';

/**
 * Daily pick with additional info.
 */
export interface DailyPickResponse {
  /**
   * @minimum 1
   * @maximum 5
   */
  rank: number;
  prediction: PredictionResponse;
  /** Combined value × confidence score */
  pick_score: number;
}
