/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { DataQualityCheckResponse } from './dataQualityCheckResponse';
import type { DataQualityResponseAnomaliesItem } from './dataQualityResponseAnomaliesItem';
import type { DataQualityResponseMetrics } from './dataQualityResponseMetrics';

/**
 * Complete data quality report.
 */
export interface DataQualityResponse {
  timestamp: string;
  overall_status: string;
  freshness: DataQualityCheckResponse;
  completeness: DataQualityCheckResponse;
  range_validation: DataQualityCheckResponse;
  consistency: DataQualityCheckResponse;
  anomalies?: DataQualityResponseAnomaliesItem[];
  metrics?: DataQualityResponseMetrics;
}
