/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */

export interface DbStatsResponse {
  total_matches: number;
  competitions_with_standings: number;
  /** @nullable */
  last_match_sync?: string | null;
  /** @nullable */
  last_standings_sync?: string | null;
}
