/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import type { DebugApiStatus200FootballApiClientHeaders } from './debugApiStatus200FootballApiClientHeaders';
import type { DebugApiStatus200FootballApiConnectivityTest } from './debugApiStatus200FootballApiConnectivityTest';

export type DebugApiStatus200FootballApi = {
  base_url?: string;
  api_key_configured?: boolean;
  api_key_length?: number;
  api_key_preview?: string;
  client_headers?: DebugApiStatus200FootballApiClientHeaders;
  connectivity_test?: DebugApiStatus200FootballApiConnectivityTest;
};
