/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */

export type DebugApiStatus200FootballApiClientHeaders = {
  configured?: boolean;
  x_auth_token_present?: boolean;
};
