/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import type { DebugApiStatus200FootballApi } from './debugApiStatus200FootballApi';
import type { DebugApiStatus200Settings } from './debugApiStatus200Settings';

export type DebugApiStatus200 = {
  football_api?: DebugApiStatus200FootballApi;
  settings?: DebugApiStatus200Settings;
};
