/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type EnrichMatchApiV1RagEnrichGetParams = {
/**
 * Home team name
 */
home_team: string;
/**
 * Away team name
 */
away_team: string;
/**
 * Competition code (PL, SA, etc.)
 */
competition?: string;
/**
 * Match date in YYYY-MM-DD format
 */
match_date?: string | null;
};
