/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { TeamFatigueInfo } from './teamFatigueInfo';

/**
 * Fatigue information for both teams in a match.
 */
export interface FatigueInfo {
  home_team: TeamFatigueInfo;
  away_team: TeamFatigueInfo;
  /**
   * Home team advantage (positive = home more rested)
   * @minimum -1
   * @maximum 1
   */
  fatigue_advantage?: number;
}
