/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Favorite response.
 */
export interface FavoriteResponse {
  id: number;
  match_id: number;
  prediction_id: number | null;
  note: string | null;
  notify_before_match: boolean;
  created_at: string;
  home_team?: string | null;
  away_team?: string | null;
  match_date?: string | null;
  competition?: string | null;
}
