/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Favorite team details.
 */
export interface FavoriteTeamInfo {
  id: number;
  name: string;
  short_name: string;
  logo_url?: string | null;
  country?: string | null;
}
