/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Team form data.
 */
export interface FormData {
  last_5?: string[];
  points?: number;
  goals_scored?: number;
  goals_conceded?: number;
  clean_sheets?: number;
  wins?: number;
  draws?: number;
  losses?: number;
  form_rating?: number;
}
