/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type GetMatchContextApiV1VectorMatchContextGetParams = {
/**
 * Home team name
 */
home_team: string;
/**
 * Away team name
 */
away_team: string;
/**
 * Competition name
 */
competition?: string | null;
};
