/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import type { GetMatchesStatus } from './getMatchesStatus';

export type GetMatchesParams = {
/**
 * Filter by competition code (e.g., PL, PD, BL1)
 */
competition?: string;
/**
 * Start date filter
 */
date_from?: string;
/**
 * End date filter
 */
date_to?: string;
status?: GetMatchesStatus;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
};
