/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type GetPredictionDebugParams = {
/**
 * @minimum 1
 * @maximum 30
 */
days?: number;
};
