/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type GetPredictionStatsParams = {
/**
 * Number of days to analyze
 * @minimum 7
 * @maximum 365
 */
days?: number;
/**
 * Force recalculation, bypass cache
 */
force_refresh?: boolean;
};
