/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type GetTennisPlayersApiV1TennisPlayersGetParams = {
/**
 * Filter by circuit (ATP, WTA)
 */
circuit?: string | null;
/**
 * Number of results
 * @minimum 1
 * @maximum 500
 */
limit?: number;
};
