/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { HeadToHeadMatch } from './headToHeadMatch';
import type { SrcApiRoutesMatchesDataSourceInfo } from './srcApiRoutesMatchesDataSourceInfo';

/**
 * Head-to-head response.
 */
export interface HeadToHeadResponse {
  matches: HeadToHeadMatch[];
  home_wins: number;
  draws: number;
  away_wins: number;
  avg_goals: number;
  total_matches: number;
  data_source?: SrcApiRoutesMatchesDataSourceInfo | null;
}
