/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * A match in head-to-head history.
 */
export interface HeadToHeadMatch {
  date: string;
  home_team: string;
  away_team: string;
  home_score: number;
  away_score: number;
  competition: string;
}
