/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { HistoricalSyncSeasonResult } from './historicalSyncSeasonResult';

/**
 * Response for multi-season historical sync.
 */
export interface HistoricalSyncResponse {
  status: string;
  total_matches_synced: number;
  seasons_synced: number;
  per_season: HistoricalSyncSeasonResult[];
  errors?: string[];
  timestamp: string;
}
