/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result for a single season sync.
 */
export interface HistoricalSyncSeasonResult {
  season: string;
  matches_synced: number;
  errors?: string[];
}
