/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result of news ingestion.
 */
export interface IngestionResult {
  team?: string | null;
  competition?: string | null;
  fetched?: number;
  indexed?: number;
  error?: string | null;
}
