/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { IngestionResult } from './ingestionResult';

/**
 * Full ingestion response.
 */
export interface IngestionResponse {
  status: string;
  total_indexed: number;
  competitions_processed?: number | null;
  teams_processed?: number | null;
  details?: IngestionResult[];
  timestamp: string;
}
