/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */

export type LastMatchResult = typeof LastMatchResult[keyof typeof LastMatchResult];


export const LastMatchResult = {
  W: 'W',
  D: 'D',
  L: 'L',
} as const;
