/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type ListBasketballMatchesApiV1BasketballMatchesGetParams = {
/**
 * Filter by league (NBA, EUROLEAGUE)
 */
league?: string | null;
/**
 * Filter by status (scheduled, live, finished)
 */
status?: string | null;
/**
 * Start date (YYYY-MM-DD)
 */
date_from?: string | null;
/**
 * End date (YYYY-MM-DD)
 */
date_to?: string | null;
/**
 * Maximum results
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * Result offset
 * @minimum 0
 */
offset?: number;
};
