/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */

export type ListMatchesStatus = typeof ListMatchesStatus[keyof typeof ListMatchesStatus];


export const ListMatchesStatus = {
  scheduled: 'scheduled',
  live: 'live',
  finished: 'finished',
} as const;
