/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type ListBasketballTeamsApiV1BasketballTeamsGetParams = {
/**
 * Filter by league (NBA, EUROLEAGUE)
 */
league?: string | null;
/**
 * Filter by conference (East, West)
 */
conference?: string | null;
};
