/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */
import type { ListMatchesStatus } from './listMatchesStatus';

export type ListMatchesParams = {
/**
 * Competition code (PL, SA, etc.)
 */
competition?: string;
/**
 * Start date (YYYY-MM-DD)
 */
date_from?: string;
/**
 * End date (YYYY-MM-DD)
 */
date_to?: string;
/**
 * Match status
 */
status?: ListMatchesStatus;
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
per_page?: number;
};
