/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Event in a live match (goal, card, etc.).
 */
export interface LiveMatchEvent {
  type: string;
  minute: number;
  team: string;
  player?: string | null;
}
