/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * LLM-derived adjustment factors.
 */
export interface LLMAdjustments {
  /**
   * @minimum -0.3
   * @maximum 0
   */
  injury_impact_home?: number;
  /**
   * @minimum -0.3
   * @maximum 0
   */
  injury_impact_away?: number;
  /**
   * @minimum -0.1
   * @maximum 0.1
   */
  sentiment_home?: number;
  /**
   * @minimum -0.1
   * @maximum 0.1
   */
  sentiment_away?: number;
  /**
   * @minimum -0.05
   * @maximum 0.05
   */
  tactical_edge?: number;
  /**
   * @minimum -0.5
   * @maximum 0.5
   */
  total_adjustment?: number;
  reasoning?: string;
}
