/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { MatchResponse } from './matchResponse';
import type { SrcApiRoutesMatchesDataSourceInfo } from './srcApiRoutesMatchesDataSourceInfo';

/**
 * List of matches response.
 */
export interface MatchListResponse {
  matches: MatchResponse[];
  total: number;
  page: number;
  per_page: number;
  data_source?: SrcApiRoutesMatchesDataSourceInfo | null;
}
