/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */
import type { Match } from './match';

export interface MatchListResponse {
  matches: Match[];
  total: number;
}
