/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import type { MatchResponseStatus } from './matchResponseStatus';
import type { TeamInfo } from './teamInfo';

export interface MatchResponse {
  id: number;
  external_id: string;
  home_team: TeamInfo;
  away_team: TeamInfo;
  competition: string;
  competition_code: string;
  match_date: string;
  status: MatchResponseStatus;
  /** @nullable */
  home_score?: number | null;
  /** @nullable */
  away_score?: number | null;
  /** @nullable */
  matchday?: number | null;
}
