/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */
import type { TeamContext } from './teamContext';

export interface MatchContext {
  home_team: string;
  away_team: string;
  competition: string;
  match_date: string;
  home_context: TeamContext;
  away_context: TeamContext;
  is_derby?: boolean;
  match_importance?: string;
  /** @nullable */
  combined_analysis?: string | null;
  enriched_at?: string;
  sources_used?: string[];
}
