/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { TeamContext } from './teamContext';

/**
 * Full match context from RAG enrichment.
 */
export interface MatchContext {
  home_team: string;
  away_team: string;
  competition: string;
  match_date: string;
  home_context: TeamContext;
  away_context: TeamContext;
  is_derby?: boolean;
  match_importance?: string;
  combined_analysis?: string | null;
  enriched_at: string;
  sources_used?: string[];
}
