/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type MatchResponseStatus = typeof MatchResponseStatus[keyof typeof MatchResponseStatus];


export const MatchResponseStatus = {
  scheduled: 'scheduled',
  live: 'live',
  finished: 'finished',
  postponed: 'postponed',
} as const;
