/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { PredictionProbabilities } from './predictionProbabilities';

/**
 * Individual model contributions to the prediction.
 */
export interface ModelContributions {
  poisson: PredictionProbabilities;
  xgboost: PredictionProbabilities;
  xg_model: PredictionProbabilities;
  elo: PredictionProbabilities;
}
