/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * News article for frontend display.
 */
export interface NewsArticle {
  title: string;
  source: string;
  published_at?: string | null;
  url?: string | null;
  article_type?: string;
  team_name?: string | null;
}
