/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Manual notification request.
 */
export interface NotificationRequest {
  title: string;
  body: string;
  url?: string;
  preference_filter?: string | null;
}
