/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for sports betting
 * OpenAPI spec version: 1.0.0
 */

export interface Odds {
  home_win: number;
  draw?: number;
  away_win: number;
}
