/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Over/Under market response.
 */
export interface OverUnderResponse {
  /** Goal line (1.5, 2.5, 3.5) */
  line: number;
  /**
   * Probability of over
   * @minimum 0
   * @maximum 1
   */
  over_prob: number;
  /**
   * Probability of under
   * @minimum 0
   * @maximum 1
   */
  under_prob: number;
  /** Bookmaker odds for over */
  over_odds?: number | null;
  /** Bookmaker odds for under */
  under_odds?: number | null;
  /** Value score for over (positive = value) */
  over_value?: number | null;
  /** Value score for under (positive = value) */
  under_value?: number | null;
  /** Recommended bet: over or under */
  recommended?: string;
}
