/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { FatigueInfo } from './fatigueInfo';
import type { LLMAdjustments } from './lLMAdjustments';
import type { ModelContributions } from './modelContributions';
import type { MultiMarketsResponse } from './multiMarketsResponse';
import type { PredictionProbabilities } from './predictionProbabilities';
import type { PredictionResponseRecommendedBet } from './predictionResponseRecommendedBet';
import type { SrcApiRoutesPredictionsDataSourceInfo } from './srcApiRoutesPredictionsDataSourceInfo';

/**
 * Full prediction response for a match.
 */
export interface PredictionResponse {
  match_id: number;
  home_team: string;
  away_team: string;
  competition: string;
  match_date: string;
  probabilities: PredictionProbabilities;
  recommended_bet: PredictionResponseRecommendedBet;
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence: number;
  /** Value vs bookmaker odds */
  value_score: number;
  explanation: string;
  key_factors: string[];
  risk_factors: string[];
  model_contributions?: ModelContributions | null;
  llm_adjustments?: LLMAdjustments | null;
  fatigue_info?: FatigueInfo | null;
  multi_markets?: MultiMarketsResponse | null;
  created_at: string;
  is_daily_pick?: boolean;
  data_source?: SrcApiRoutesPredictionsDataSourceInfo | null;
}
