/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import type { PredictionStatsResponseByBetType } from './predictionStatsResponseByBetType';
import type { PredictionStatsResponseByCompetition } from './predictionStatsResponseByCompetition';

export interface PredictionStatsResponse {
  total_predictions: number;
  correct_predictions: number;
  accuracy: number;
  roi_simulated: number;
  by_competition: PredictionStatsResponseByCompetition;
  by_bet_type: PredictionStatsResponseByBetType;
  last_updated: string;
}
