/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */

export interface PredictionProbabilities {
  /**
   * @minimum 0
   * @maximum 1
   */
  home_win: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  draw: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  away_win: number;
}
