/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Debug info about predictions data.
 */
export interface PredictionDebugResponse {
  total_predictions: number;
  verified_predictions: number;
  finished_matches_with_predictions: number;
  pending_verification: number;
  message: string;
}
