/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */

export type PredictionResponseRecommendedBet = typeof PredictionResponseRecommendedBet[keyof typeof PredictionResponseRecommendedBet];


export const PredictionResponseRecommendedBet = {
  home_win: 'home_win',
  draw: 'draw',
  away_win: 'away_win',
} as const;
