/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * User preferences.
 */
export interface PreferencesResponse {
  language: string;
  timezone: string;
  odds_format: string;
  dark_mode: boolean;
  email_daily_picks: boolean;
  email_match_results: boolean;
  push_daily_picks: boolean;
  push_match_start: boolean;
  push_bet_results: boolean;
  default_stake: number;
  risk_level: string;
  favorite_competitions: string[];
}
