/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { PrefillResponseTeamData } from './prefillResponseTeamData';

/**
 * Data prefill response.
 */
export interface PrefillResponse {
  status: string;
  team_data: PrefillResponseTeamData;
  elo_ratings: number;
  predictions: number;
  redis_cache: number;
  duration_seconds: number;
  timestamp: string;
}
