/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */

export interface RAGStatusResponse {
  enabled: boolean;
  groq_configured: boolean;
  /** @nullable */
  last_enrichment?: string | null;
  total_enrichments: number;
}
