/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type SearchNewsApiV1VectorSearchGetParams = {
/**
 * Search query
 * @minLength 3
 */
query: string;
/**
 * Filter by team name
 */
team_name?: string | null;
/**
 * Filter by type (injury, transfer, form)
 */
article_type?: string | null;
/**
 * Max results
 * @minimum 1
 * @maximum 20
 */
limit?: number;
};
