/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { SearchApiV1SearchGetType } from './searchApiV1SearchGetType';

export type SearchApiV1SearchGetParams = {
/**
 * Search query
 * @minLength 2
 * @maxLength 100
 */
q: string;
/**
 * Filter by result type
 */
type?: SearchApiV1SearchGetType;
/**
 * Max results per category
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
