/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type SearchTeamsApiV1UsersTeamsSearchGetParams = {
/**
 * Search query (min 2 characters)
 * @minLength 2
 */
q: string;
/**
 * Maximum results to return
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
