/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * A team returned by search.
 */
export interface SrcApiRoutesSearchTeamSearchResult {
  id: number;
  name: string;
  short_name?: string | null;
  tla?: string | null;
  country?: string | null;
  logo_url?: string | null;
}
