/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */
import type { StandingTeamResponse } from './standingTeamResponse';

export interface StandingsResponse {
  competition_code: string;
  competition_name: string;
  standings: StandingTeamResponse[];
  /** @nullable */
  last_updated?: string | null;
}
