/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { PushKeys } from './pushKeys';

/**
 * Push subscription request from browser.
 */
export interface SubscriptionRequest {
  endpoint: string;
  expirationTime?: number | null;
  keys: PushKeys;
}
