/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 1.0.0
 */

export type SyncWeeklyDataParams = {
/**
 * Number of days to sync
 * @minimum 1
 * @maximum 14
 */
days?: number;
/**
 * Also sync standings
 */
include_standings?: boolean;
};
