/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type SyncHistoricalSeasonApiV1SyncHistoricalPostParams = {
/**
 * Season start date (default: Aug 1, 2025)
 */
season_start?: string;
};
