/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Team summary with RAG-generated content.
 */
export interface TeamSummaryResponse {
  team_id: number;
  team_name: string;
  summary: string;
  form: string[];
  position?: number | null;
  points?: number | null;
  competition?: string | null;
  injuries_count?: number;
  generated_at: string;
}
