/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Fatigue information for a single team.
 */
export interface TeamFatigueInfo {
  /**
   * Rest days score (0=fatigued, 1=well-rested)
   * @minimum 0
   * @maximum 1
   */
  rest_days_score?: number;
  /**
   * Fixture congestion score (0=congested, 1=light)
   * @minimum 0
   * @maximum 1
   */
  fixture_congestion_score?: number;
  /**
   * Combined fatigue score
   * @minimum 0
   * @maximum 1
   */
  combined_score?: number;
}
