/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

export type TeamFormMatchHomeAway = typeof TeamFormMatchHomeAway[keyof typeof TeamFormMatchHomeAway];


export const TeamFormMatchHomeAway = {
  H: 'H',
  A: 'A',
} as const;
