/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API for football predictions and sports betting analysis
 * OpenAPI spec version: 1.0.0
 */

export interface TeamContext {
  team_name: string;
  recent_news?: string[];
  injuries?: string[];
  sentiment_score?: number;
  sentiment_label?: string;
}
