/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import type { TennisPlayerResponse } from './tennisPlayerResponse';
import type { TennisTournamentResponse } from './tennisTournamentResponse';

/**
 * Tennis match response.
 */
export interface TennisMatchResponse {
  id: number;
  player1: TennisPlayerResponse;
  player2: TennisPlayerResponse;
  tournament: TennisTournamentResponse;
  round?: string | null;
  match_date: string;
  surface: string;
  status: string;
  winner_id?: number | null;
  score?: string | null;
  sets_player1?: number | null;
  sets_player2?: number | null;
  odds_player1?: number | null;
  odds_player2?: number | null;
  pred_player1_prob?: number | null;
  pred_player2_prob?: number | null;
  pred_confidence?: number | null;
  pred_explanation?: string | null;
}
