/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Tennis player response.
 */
export interface TennisPlayerResponse {
  id: number;
  name: string;
  country?: string | null;
  photo_url?: string | null;
  circuit: string;
  atp_ranking?: number | null;
  wta_ranking?: number | null;
  elo_hard: number;
  elo_clay: number;
  elo_grass: number;
  elo_indoor: number;
  win_rate_ytd?: number | null;
}
