/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Single testimonial response.
 */
export interface TestimonialResponse {
  id: number;
  author_name: string;
  author_role?: string | null;
  content: string;
  rating: number;
  avatar_url?: string | null;
  created_at: string;
}
