/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single match for ML training.
 */
export interface TrainingMatch {
  home_attack: number;
  home_defense: number;
  away_attack: number;
  away_defense: number;
  home_elo: number;
  away_elo: number;
  home_form: number;
  away_form: number;
  home_rest_days: number;
  away_rest_days: number;
  home_fixture_congestion: number;
  away_fixture_congestion: number;
  result: number;
}
