/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * User statistics response.
 */
export interface UserStatsResponse {
  total_predictions_viewed?: number;
  favorite_competition?: string | null;
  member_since_days?: number;
}
