/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * User preferences update request.
 */
export interface UserPreferencesUpdate {
  language?: string | null;
  timezone?: string | null;
  odds_format?: string | null;
  dark_mode?: boolean | null;
  email_daily_picks?: boolean | null;
  email_match_results?: boolean | null;
  push_daily_picks?: boolean | null;
  push_match_start?: boolean | null;
  push_bet_results?: boolean | null;
  default_stake?: number | null;
  risk_level?: string | null;
  favorite_competitions?: string[] | null;
  favorite_team_id?: number | null;
}
