/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Vector store statistics.
 */
export interface VectorStoreStats {
  collection: string;
  total_vectors: number;
  embedding_dimension?: number;
  status?: string;
}
