/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for verifying a prediction.
 */
export interface VerifyPredictionRequest {
  /**
   * Final home team score
   * @minimum 0
   */
  home_score: number;
  /**
   * Final away team score
   * @minimum 0
   */
  away_score: number;
}
