/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response for prediction verification.
 */
export interface VerifyPredictionsResponse {
  status: string;
  verified_count: number;
  already_verified: number;
  total_unverified: number;
  timestamp: string;
}
