/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response after verifying a prediction.
 */
export interface VerifyPredictionResponse {
  match_id: number;
  home_score: number;
  away_score: number;
  actual_result: string;
  was_correct: boolean;
  message: string;
}
