/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Comparison of version metrics.
 */
export interface VersionComparison {
  version_id: string;
  is_baseline: boolean;
  sample_count: number;
  accuracy: number;
  avg_brier_score: number;
  avg_latency_ms: number;
  accuracy_vs_baseline?: number | null;
  brier_vs_baseline?: number | null;
}
