/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to create a new prompt version.
 */
export interface VersionCreate {
  /** Type of prompt (e.g., injury_analysis) */
  prompt_type: string;
  /** Prompt template with placeholders */
  template: string;
  /** Description of this version */
  description: string;
  /** Optional version suffix */
  version_suffix?: string | null;
}
