/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Match weather data.
 */
export interface WeatherData {
  available?: boolean;
  temperature?: number | null;
  feels_like?: number | null;
  humidity?: number | null;
  description?: string | null;
  wind_speed?: number | null;
  rain_probability?: number | null;
  impact?: string | null;
}
