/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Paris Sportif API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */

/**
 * Estimated xG metrics.
 */
export interface XGEstimate {
  estimated_xg?: number;
  estimated_xga?: number;
  offensive_rating?: number;
  defensive_rating?: number;
}
