/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CancelRequest,
  CheckoutResponse,
  CreateCheckoutRequest,
  HTTPValidationError,
  PortalRequest,
  PortalResponse,
  SubscriptionResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a Stripe Checkout session for subscription purchase.

Requires authentication. Creates a checkout session for the specified plan
with a 7-day free trial.
 * @summary Create Checkout Session
 */
export type createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponse200 = {
  data: CheckoutResponse
  status: 200
}

export type createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponseSuccess = (createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponse200) & {
  headers: Headers;
};
export type createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponseError = (createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponse422) & {
  headers: Headers;
};

export type createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponse = (createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponseSuccess | createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponseError)

export const getCreateCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostUrl = () => {


  

  return `/api/v1/stripe/stripe/create-checkout-session`
}

export const createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost = async (createCheckoutRequest: CreateCheckoutRequest, options?: RequestInit): Promise<createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponse> => {
  
  return customInstance<createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostResponse>(getCreateCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCheckoutRequest,)
  }
);}




export const getCreateCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost>>, TError,{data: CreateCheckoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost>>, TError,{data: CreateCheckoutRequest}, TContext> => {

const mutationKey = ['createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost>>, {data: CreateCheckoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost>>>
    export type CreateCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostMutationBody = CreateCheckoutRequest
    export type CreateCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostMutationError = HTTPValidationError

    /**
 * @summary Create Checkout Session
 */
export const useCreateCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost>>, TError,{data: CreateCheckoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPost>>,
        TError,
        {data: CreateCheckoutRequest},
        TContext
      > => {
      return useMutation(getCreateCheckoutSessionApiV1StripeStripeCreateCheckoutSessionPostMutationOptions(options), queryClient);
    }
    /**
 * Create a Stripe Customer Portal session for subscription management.

Allows users to manage their subscription, update payment methods,
view invoices, and cancel.
 * @summary Create Portal Session
 */
export type createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponse200 = {
  data: PortalResponse
  status: 200
}

export type createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponseSuccess = (createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponse200) & {
  headers: Headers;
};
export type createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponseError = (createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponse422) & {
  headers: Headers;
};

export type createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponse = (createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponseSuccess | createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponseError)

export const getCreatePortalSessionApiV1StripeStripeCreatePortalSessionPostUrl = () => {


  

  return `/api/v1/stripe/stripe/create-portal-session`
}

export const createPortalSessionApiV1StripeStripeCreatePortalSessionPost = async (portalRequest: PortalRequest, options?: RequestInit): Promise<createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponse> => {
  
  return customInstance<createPortalSessionApiV1StripeStripeCreatePortalSessionPostResponse>(getCreatePortalSessionApiV1StripeStripeCreatePortalSessionPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      portalRequest,)
  }
);}




export const getCreatePortalSessionApiV1StripeStripeCreatePortalSessionPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1StripeStripeCreatePortalSessionPost>>, TError,{data: PortalRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1StripeStripeCreatePortalSessionPost>>, TError,{data: PortalRequest}, TContext> => {

const mutationKey = ['createPortalSessionApiV1StripeStripeCreatePortalSessionPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPortalSessionApiV1StripeStripeCreatePortalSessionPost>>, {data: PortalRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPortalSessionApiV1StripeStripeCreatePortalSessionPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePortalSessionApiV1StripeStripeCreatePortalSessionPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPortalSessionApiV1StripeStripeCreatePortalSessionPost>>>
    export type CreatePortalSessionApiV1StripeStripeCreatePortalSessionPostMutationBody = PortalRequest
    export type CreatePortalSessionApiV1StripeStripeCreatePortalSessionPostMutationError = HTTPValidationError

    /**
 * @summary Create Portal Session
 */
export const useCreatePortalSessionApiV1StripeStripeCreatePortalSessionPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1StripeStripeCreatePortalSessionPost>>, TError,{data: PortalRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPortalSessionApiV1StripeStripeCreatePortalSessionPost>>,
        TError,
        {data: PortalRequest},
        TContext
      > => {
      return useMutation(getCreatePortalSessionApiV1StripeStripeCreatePortalSessionPostMutationOptions(options), queryClient);
    }
    /**
 * Get the current user's subscription details.

Returns None if no active subscription exists.
 * @summary Get Subscription
 */
export type getSubscriptionApiV1StripeStripeSubscriptionGetResponse200 = {
  data: SubscriptionResponse | null
  status: 200
}
    
export type getSubscriptionApiV1StripeStripeSubscriptionGetResponseSuccess = (getSubscriptionApiV1StripeStripeSubscriptionGetResponse200) & {
  headers: Headers;
};
;

export type getSubscriptionApiV1StripeStripeSubscriptionGetResponse = (getSubscriptionApiV1StripeStripeSubscriptionGetResponseSuccess)

export const getGetSubscriptionApiV1StripeStripeSubscriptionGetUrl = () => {


  

  return `/api/v1/stripe/stripe/subscription`
}

export const getSubscriptionApiV1StripeStripeSubscriptionGet = async ( options?: RequestInit): Promise<getSubscriptionApiV1StripeStripeSubscriptionGetResponse> => {
  
  return customInstance<getSubscriptionApiV1StripeStripeSubscriptionGetResponse>(getGetSubscriptionApiV1StripeStripeSubscriptionGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSubscriptionApiV1StripeStripeSubscriptionGetQueryKey = () => {
    return [
    `/api/v1/stripe/stripe/subscription`
    ] as const;
    }

    
export const getGetSubscriptionApiV1StripeStripeSubscriptionGetQueryOptions = <TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSubscriptionApiV1StripeStripeSubscriptionGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>> = ({ signal }) => getSubscriptionApiV1StripeStripeSubscriptionGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSubscriptionApiV1StripeStripeSubscriptionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>>
export type GetSubscriptionApiV1StripeStripeSubscriptionGetQueryError = unknown


export function useGetSubscriptionApiV1StripeStripeSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubscriptionApiV1StripeStripeSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubscriptionApiV1StripeStripeSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Subscription
 */

export function useGetSubscriptionApiV1StripeStripeSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeStripeSubscriptionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSubscriptionApiV1StripeStripeSubscriptionGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Cancel the current user's subscription.

By default, cancels at the end of the billing period.
Set immediate=True to cancel immediately.
 * @summary Cancel Subscription
 */
export type cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponse200 = {
  data: unknown
  status: 200
}

export type cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponseSuccess = (cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponse200) & {
  headers: Headers;
};
export type cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponseError = (cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponse422) & {
  headers: Headers;
};

export type cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponse = (cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponseSuccess | cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponseError)

export const getCancelSubscriptionApiV1StripeStripeCancelSubscriptionPostUrl = () => {


  

  return `/api/v1/stripe/stripe/cancel-subscription`
}

export const cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost = async (cancelRequest: CancelRequest, options?: RequestInit): Promise<cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponse> => {
  
  return customInstance<cancelSubscriptionApiV1StripeStripeCancelSubscriptionPostResponse>(getCancelSubscriptionApiV1StripeStripeCancelSubscriptionPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      cancelRequest,)
  }
);}




export const getCancelSubscriptionApiV1StripeStripeCancelSubscriptionPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost>>, TError,{data: CancelRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost>>, TError,{data: CancelRequest}, TContext> => {

const mutationKey = ['cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost>>, {data: CancelRequest}> = (props) => {
          const {data} = props ?? {};

          return  cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CancelSubscriptionApiV1StripeStripeCancelSubscriptionPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost>>>
    export type CancelSubscriptionApiV1StripeStripeCancelSubscriptionPostMutationBody = CancelRequest
    export type CancelSubscriptionApiV1StripeStripeCancelSubscriptionPostMutationError = HTTPValidationError

    /**
 * @summary Cancel Subscription
 */
export const useCancelSubscriptionApiV1StripeStripeCancelSubscriptionPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost>>, TError,{data: CancelRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeStripeCancelSubscriptionPost>>,
        TError,
        {data: CancelRequest},
        TContext
      > => {
      return useMutation(getCancelSubscriptionApiV1StripeStripeCancelSubscriptionPostMutationOptions(options), queryClient);
    }
    /**
 * Handle Stripe webhook events.

Events handled:
- checkout.session.completed: User completed checkout
- customer.subscription.created: Subscription started
- customer.subscription.updated: Subscription changed
- customer.subscription.deleted: Subscription cancelled
- invoice.paid: Payment successful
- invoice.payment_failed: Payment failed
 * @summary Stripe Webhook
 */
export type stripeWebhookApiV1StripeStripeWebhookPostResponse200 = {
  data: unknown
  status: 200
}

export type stripeWebhookApiV1StripeStripeWebhookPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type stripeWebhookApiV1StripeStripeWebhookPostResponseSuccess = (stripeWebhookApiV1StripeStripeWebhookPostResponse200) & {
  headers: Headers;
};
export type stripeWebhookApiV1StripeStripeWebhookPostResponseError = (stripeWebhookApiV1StripeStripeWebhookPostResponse422) & {
  headers: Headers;
};

export type stripeWebhookApiV1StripeStripeWebhookPostResponse = (stripeWebhookApiV1StripeStripeWebhookPostResponseSuccess | stripeWebhookApiV1StripeStripeWebhookPostResponseError)

export const getStripeWebhookApiV1StripeStripeWebhookPostUrl = () => {


  

  return `/api/v1/stripe/stripe/webhook`
}

export const stripeWebhookApiV1StripeStripeWebhookPost = async ( options?: RequestInit): Promise<stripeWebhookApiV1StripeStripeWebhookPostResponse> => {
  
  return customInstance<stripeWebhookApiV1StripeStripeWebhookPostResponse>(getStripeWebhookApiV1StripeStripeWebhookPostUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getStripeWebhookApiV1StripeStripeWebhookPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1StripeStripeWebhookPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1StripeStripeWebhookPost>>, TError,void, TContext> => {

const mutationKey = ['stripeWebhookApiV1StripeStripeWebhookPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stripeWebhookApiV1StripeStripeWebhookPost>>, void> = () => {
          

          return  stripeWebhookApiV1StripeStripeWebhookPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StripeWebhookApiV1StripeStripeWebhookPostMutationResult = NonNullable<Awaited<ReturnType<typeof stripeWebhookApiV1StripeStripeWebhookPost>>>
    
    export type StripeWebhookApiV1StripeStripeWebhookPostMutationError = HTTPValidationError

    /**
 * @summary Stripe Webhook
 */
export const useStripeWebhookApiV1StripeStripeWebhookPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1StripeStripeWebhookPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stripeWebhookApiV1StripeStripeWebhookPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getStripeWebhookApiV1StripeStripeWebhookPostMutationOptions(options), queryClient);
    }
    