/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * WinRate AI API
 * API de predictions de paris sportifs sur le football europeen
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CancelRequest,
  CancelSubscriptionApiV1StripeCancelSubscriptionPost200,
  CheckoutResponse,
  CreateCheckoutRequest,
  HTTPValidationError,
  PortalRequest,
  PortalResponse,
  StripeWebhookApiV1StripeWebhookPost200,
  SubscriptionResponse
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a Stripe Checkout session for subscription purchase.

Requires authentication. Creates a checkout session for the specified plan
with a 7-day free trial.
 * @summary Create Checkout Session
 */
export type createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponse200 = {
  data: CheckoutResponse
  status: 200
}

export type createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponseSuccess = (createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponse200) & {
  headers: Headers;
};
export type createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponseError = (createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponse422) & {
  headers: Headers;
};

export type createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponse = (createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponseSuccess | createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponseError)

export const getCreateCheckoutSessionApiV1StripeCreateCheckoutSessionPostUrl = () => {


  

  return `/api/v1/stripe/create-checkout-session`
}

export const createCheckoutSessionApiV1StripeCreateCheckoutSessionPost = async (createCheckoutRequest: CreateCheckoutRequest, options?: RequestInit): Promise<createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponse> => {
  
  return customInstance<createCheckoutSessionApiV1StripeCreateCheckoutSessionPostResponse>(getCreateCheckoutSessionApiV1StripeCreateCheckoutSessionPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCheckoutRequest,)
  }
);}




export const getCreateCheckoutSessionApiV1StripeCreateCheckoutSessionPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeCreateCheckoutSessionPost>>, TError,{data: CreateCheckoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeCreateCheckoutSessionPost>>, TError,{data: CreateCheckoutRequest}, TContext> => {

const mutationKey = ['createCheckoutSessionApiV1StripeCreateCheckoutSessionPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeCreateCheckoutSessionPost>>, {data: CreateCheckoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCheckoutSessionApiV1StripeCreateCheckoutSessionPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCheckoutSessionApiV1StripeCreateCheckoutSessionPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeCreateCheckoutSessionPost>>>
    export type CreateCheckoutSessionApiV1StripeCreateCheckoutSessionPostMutationBody = CreateCheckoutRequest
    export type CreateCheckoutSessionApiV1StripeCreateCheckoutSessionPostMutationError = HTTPValidationError

    /**
 * @summary Create Checkout Session
 */
export const useCreateCheckoutSessionApiV1StripeCreateCheckoutSessionPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeCreateCheckoutSessionPost>>, TError,{data: CreateCheckoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCheckoutSessionApiV1StripeCreateCheckoutSessionPost>>,
        TError,
        {data: CreateCheckoutRequest},
        TContext
      > => {
      return useMutation(getCreateCheckoutSessionApiV1StripeCreateCheckoutSessionPostMutationOptions(options), queryClient);
    }
    /**
 * Create a Stripe Customer Portal session for subscription management.

Allows users to manage their subscription, update payment methods,
view invoices, and cancel.
 * @summary Create Portal Session
 */
export type createPortalSessionApiV1StripeCreatePortalSessionPostResponse200 = {
  data: PortalResponse
  status: 200
}

export type createPortalSessionApiV1StripeCreatePortalSessionPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createPortalSessionApiV1StripeCreatePortalSessionPostResponseSuccess = (createPortalSessionApiV1StripeCreatePortalSessionPostResponse200) & {
  headers: Headers;
};
export type createPortalSessionApiV1StripeCreatePortalSessionPostResponseError = (createPortalSessionApiV1StripeCreatePortalSessionPostResponse422) & {
  headers: Headers;
};

export type createPortalSessionApiV1StripeCreatePortalSessionPostResponse = (createPortalSessionApiV1StripeCreatePortalSessionPostResponseSuccess | createPortalSessionApiV1StripeCreatePortalSessionPostResponseError)

export const getCreatePortalSessionApiV1StripeCreatePortalSessionPostUrl = () => {


  

  return `/api/v1/stripe/create-portal-session`
}

export const createPortalSessionApiV1StripeCreatePortalSessionPost = async (portalRequest: PortalRequest, options?: RequestInit): Promise<createPortalSessionApiV1StripeCreatePortalSessionPostResponse> => {
  
  return customInstance<createPortalSessionApiV1StripeCreatePortalSessionPostResponse>(getCreatePortalSessionApiV1StripeCreatePortalSessionPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      portalRequest,)
  }
);}




export const getCreatePortalSessionApiV1StripeCreatePortalSessionPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1StripeCreatePortalSessionPost>>, TError,{data: PortalRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1StripeCreatePortalSessionPost>>, TError,{data: PortalRequest}, TContext> => {

const mutationKey = ['createPortalSessionApiV1StripeCreatePortalSessionPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPortalSessionApiV1StripeCreatePortalSessionPost>>, {data: PortalRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPortalSessionApiV1StripeCreatePortalSessionPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePortalSessionApiV1StripeCreatePortalSessionPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPortalSessionApiV1StripeCreatePortalSessionPost>>>
    export type CreatePortalSessionApiV1StripeCreatePortalSessionPostMutationBody = PortalRequest
    export type CreatePortalSessionApiV1StripeCreatePortalSessionPostMutationError = HTTPValidationError

    /**
 * @summary Create Portal Session
 */
export const useCreatePortalSessionApiV1StripeCreatePortalSessionPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1StripeCreatePortalSessionPost>>, TError,{data: PortalRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPortalSessionApiV1StripeCreatePortalSessionPost>>,
        TError,
        {data: PortalRequest},
        TContext
      > => {
      return useMutation(getCreatePortalSessionApiV1StripeCreatePortalSessionPostMutationOptions(options), queryClient);
    }
    /**
 * Get the current user's subscription details.

Returns None if no active subscription exists.
 * @summary Get Subscription
 */
export type getSubscriptionApiV1StripeSubscriptionGetResponse200 = {
  data: SubscriptionResponse | null
  status: 200
}
    
export type getSubscriptionApiV1StripeSubscriptionGetResponseSuccess = (getSubscriptionApiV1StripeSubscriptionGetResponse200) & {
  headers: Headers;
};
;

export type getSubscriptionApiV1StripeSubscriptionGetResponse = (getSubscriptionApiV1StripeSubscriptionGetResponseSuccess)

export const getGetSubscriptionApiV1StripeSubscriptionGetUrl = () => {


  

  return `/api/v1/stripe/subscription`
}

export const getSubscriptionApiV1StripeSubscriptionGet = async ( options?: RequestInit): Promise<getSubscriptionApiV1StripeSubscriptionGetResponse> => {
  
  return customInstance<getSubscriptionApiV1StripeSubscriptionGetResponse>(getGetSubscriptionApiV1StripeSubscriptionGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSubscriptionApiV1StripeSubscriptionGetQueryKey = () => {
    return [
    `/api/v1/stripe/subscription`
    ] as const;
    }

    
export const getGetSubscriptionApiV1StripeSubscriptionGetQueryOptions = <TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSubscriptionApiV1StripeSubscriptionGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>> = ({ signal }) => getSubscriptionApiV1StripeSubscriptionGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSubscriptionApiV1StripeSubscriptionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>>
export type GetSubscriptionApiV1StripeSubscriptionGetQueryError = unknown


export function useGetSubscriptionApiV1StripeSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubscriptionApiV1StripeSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubscriptionApiV1StripeSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Subscription
 */

export function useGetSubscriptionApiV1StripeSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionApiV1StripeSubscriptionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSubscriptionApiV1StripeSubscriptionGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Cancel the current user's subscription.

By default, cancels at the end of the billing period.
Set immediate=True to cancel immediately.
 * @summary Cancel Subscription
 */
export type cancelSubscriptionApiV1StripeCancelSubscriptionPostResponse200 = {
  data: CancelSubscriptionApiV1StripeCancelSubscriptionPost200
  status: 200
}

export type cancelSubscriptionApiV1StripeCancelSubscriptionPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type cancelSubscriptionApiV1StripeCancelSubscriptionPostResponseSuccess = (cancelSubscriptionApiV1StripeCancelSubscriptionPostResponse200) & {
  headers: Headers;
};
export type cancelSubscriptionApiV1StripeCancelSubscriptionPostResponseError = (cancelSubscriptionApiV1StripeCancelSubscriptionPostResponse422) & {
  headers: Headers;
};

export type cancelSubscriptionApiV1StripeCancelSubscriptionPostResponse = (cancelSubscriptionApiV1StripeCancelSubscriptionPostResponseSuccess | cancelSubscriptionApiV1StripeCancelSubscriptionPostResponseError)

export const getCancelSubscriptionApiV1StripeCancelSubscriptionPostUrl = () => {


  

  return `/api/v1/stripe/cancel-subscription`
}

export const cancelSubscriptionApiV1StripeCancelSubscriptionPost = async (cancelRequest: CancelRequest, options?: RequestInit): Promise<cancelSubscriptionApiV1StripeCancelSubscriptionPostResponse> => {
  
  return customInstance<cancelSubscriptionApiV1StripeCancelSubscriptionPostResponse>(getCancelSubscriptionApiV1StripeCancelSubscriptionPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      cancelRequest,)
  }
);}




export const getCancelSubscriptionApiV1StripeCancelSubscriptionPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeCancelSubscriptionPost>>, TError,{data: CancelRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeCancelSubscriptionPost>>, TError,{data: CancelRequest}, TContext> => {

const mutationKey = ['cancelSubscriptionApiV1StripeCancelSubscriptionPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeCancelSubscriptionPost>>, {data: CancelRequest}> = (props) => {
          const {data} = props ?? {};

          return  cancelSubscriptionApiV1StripeCancelSubscriptionPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CancelSubscriptionApiV1StripeCancelSubscriptionPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeCancelSubscriptionPost>>>
    export type CancelSubscriptionApiV1StripeCancelSubscriptionPostMutationBody = CancelRequest
    export type CancelSubscriptionApiV1StripeCancelSubscriptionPostMutationError = HTTPValidationError

    /**
 * @summary Cancel Subscription
 */
export const useCancelSubscriptionApiV1StripeCancelSubscriptionPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeCancelSubscriptionPost>>, TError,{data: CancelRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelSubscriptionApiV1StripeCancelSubscriptionPost>>,
        TError,
        {data: CancelRequest},
        TContext
      > => {
      return useMutation(getCancelSubscriptionApiV1StripeCancelSubscriptionPostMutationOptions(options), queryClient);
    }
    /**
 * Handle Stripe webhook events.

Events handled:
- checkout.session.completed: User completed checkout
- customer.subscription.created: Subscription started
- customer.subscription.updated: Subscription changed
- customer.subscription.deleted: Subscription cancelled
- invoice.paid: Payment successful
- invoice.payment_failed: Payment failed
 * @summary Stripe Webhook
 */
export type stripeWebhookApiV1StripeWebhookPostResponse200 = {
  data: StripeWebhookApiV1StripeWebhookPost200
  status: 200
}

export type stripeWebhookApiV1StripeWebhookPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type stripeWebhookApiV1StripeWebhookPostResponseSuccess = (stripeWebhookApiV1StripeWebhookPostResponse200) & {
  headers: Headers;
};
export type stripeWebhookApiV1StripeWebhookPostResponseError = (stripeWebhookApiV1StripeWebhookPostResponse422) & {
  headers: Headers;
};

export type stripeWebhookApiV1StripeWebhookPostResponse = (stripeWebhookApiV1StripeWebhookPostResponseSuccess | stripeWebhookApiV1StripeWebhookPostResponseError)

export const getStripeWebhookApiV1StripeWebhookPostUrl = () => {


  

  return `/api/v1/stripe/webhook`
}

export const stripeWebhookApiV1StripeWebhookPost = async ( options?: RequestInit): Promise<stripeWebhookApiV1StripeWebhookPostResponse> => {
  
  return customInstance<stripeWebhookApiV1StripeWebhookPostResponse>(getStripeWebhookApiV1StripeWebhookPostUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getStripeWebhookApiV1StripeWebhookPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1StripeWebhookPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1StripeWebhookPost>>, TError,void, TContext> => {

const mutationKey = ['stripeWebhookApiV1StripeWebhookPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stripeWebhookApiV1StripeWebhookPost>>, void> = () => {
          

          return  stripeWebhookApiV1StripeWebhookPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StripeWebhookApiV1StripeWebhookPostMutationResult = NonNullable<Awaited<ReturnType<typeof stripeWebhookApiV1StripeWebhookPost>>>
    
    export type StripeWebhookApiV1StripeWebhookPostMutationError = HTTPValidationError

    /**
 * @summary Stripe Webhook
 */
export const useStripeWebhookApiV1StripeWebhookPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1StripeWebhookPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stripeWebhookApiV1StripeWebhookPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getStripeWebhookApiV1StripeWebhookPostMutationOptions(options), queryClient);
    }
    